### ISSUE TITLE
java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by Protoxy22** [bernie-g/geckolib#1]
`---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 6/30/20 2:55 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access field net.minecraft.client.model.ModelRenderer.field_78803_o from class software.bernie.geckolib.animation.model.AnimatedModelRenderer
	at software.bernie.geckolib.animation.model.AnimatedModelRenderer.setTextureOffset(AnimatedModelRenderer.java:42)
	at software.bernie.geckolib.example.client.renderer.model.TigrisModel.<init>(TigrisModel.java:51)
	at software.bernie.geckolib.example.client.renderer.entity.TigrisRenderer.<init>(TigrisRenderer.java:20)
	at software.bernie.geckolib.ModEventBus$$Lambda$72/541840685.createRenderFor(Unknown Source)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.register(RenderingRegistry.java:77)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:70)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:230)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at software.bernie.geckolib.animation.model.AnimatedModelRenderer.setTextureOffset(AnimatedModelRenderer.java:42)
	at software.bernie.geckolib.example.client.renderer.model.TigrisModel.<init>(TigrisModel.java:51)
	at software.bernie.geckolib.example.client.renderer.entity.TigrisRenderer.<init>(TigrisRenderer.java:20)
	at software.bernie.geckolib.ModEventBus$$Lambda$72/541840685.createRenderFor(Unknown Source)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.register(RenderingRegistry.java:77)
	at net.minecraftforge.fml.client.registry.RenderingRegistry.loadEntityRenderers(RenderingRegistry.java:70)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:230)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 495476208 bytes (472 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCH   | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCH   | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCH   | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge     | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | geckolib  | 1.0.0        | geckolib-1.12-1.0.0.jar       | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.66' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.66, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Faithful (1.13+).zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz`

**Comment by bernie-g** [comment]
You need to add this to your gradle in the minecraft section:

useDepAts = true

**Comment by AtlasThe1st** [comment]
> You need to add this to your gradle in the minecraft section:
> 
> useDepAts = true

Still crashes with that in the minecraft section, also crashes outside of the dev environment

**Comment by bernie-g** [comment]
@AtlasThe1st My bad, just fixed that in [1.12-1.0.1](https://www.curseforge.com/minecraft/mc-mods/geckolib/files/2997935)

Make sure you update your dependency in your build.gradle to this:
`com.github.bernie-g:geckolib:1.12-1.0.1`

**Comment by bernie-g** [comment]
Closing this issue as it appears to be fixed.
