### ISSUE TITLE
Crash when loading and creating worlds

### ISSUE THREAD

**Issue by maximumpower55** [bernie-g/geckolib#112]
Minecraft Version: 1.16.5
Forge Version: 36.0.39
GeckoLib Version: 3.0.14

Ask me If you need the full log

Error:
[16:47:05] [ForkJoinPool.commonPool-worker-31/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: Could not find parent software/bernie/geckolib3/core/keyframe/EventKeyFrame for class software/bernie/geckolib3/core/keyframe/ParticleEventKeyFrame in classloader jdk.internal.loader.ClassLoaders$AppClassLoader@4e0e2f2a on thread Thread[ForkJoinPool.commonPool-worker-31,10,main]
[16:47:05] [ForkJoinPool.commonPool-worker-31/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.ClassNotFoundException: software.bernie.geckolib3.core.keyframe.EventKeyFrame
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606) ~[?:?] {}
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-4.0.0.jar:4.0.0+65+master.6080a3f] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
	at software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:233) ~[?:?] {re:classloading}
	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:31) ~[?:?] {re:classloading}
	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$null$3(GeckoLibCache.java:71) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?] {}
...

**Comment by bernie-g** [comment]
What java version? Is this in dev or prod?

**Comment by maximumpower55** [comment]
java 15 64 bit
production

**Comment by bernie-g** [comment]
You have to use Java 8
