### ISSUE TITLE
Crashed when I did F3+T

### ISSUE THREAD

**Issue by aaronhowser1** [bernie-g/geckolib#139]
https://pastebin.com/dygCiHpZ

```
java.lang.NullPointerException: Rendering entity in world
	at software.bernie.shadowed.eliotlash.molang.MolangParser.getVariable(MolangParser.java:87) ~[geckolib3:3.0.36] {re:classloading}
	at software.bernie.shadowed.eliotlash.molang.MolangParser.setValue(MolangParser.java:73) ~[geckolib3:3.0.36] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setMolangQueries(AnimatedGeoModel.java:127) ~[geckolib3:3.0.36] {re:classloading}
	at software.bernie.geckolib3.core.processor.AnimationProcessor.preAnimationSetup(AnimationProcessor.java:296) ~[geckolib3:3.0.36] {re:classloading}
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:74) ~[geckolib3:3.0.36] {re:classloading}
	at com.hollingsworth.arsnouveau.client.renderer.entity.WixieModel.setLivingAnimations(WixieModel.java:20) ~[ars_nouveau:1.17] {re:classloading}
	at com.hollingsworth.arsnouveau.client.renderer.entity.WixieModel.setLivingAnimations(WixieModel.java:13) ~[ars_nouveau:1.17] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:136) ~[geckolib3:3.0.36] {re:classloading}
	at com.hollingsworth.arsnouveau.client.renderer.entity.WixieRenderer.render(WixieRenderer.java:24) ~[ars_nouveau:1.17] {re:classloading}
	at com.hollingsworth.arsnouveau.client.renderer.entity.WixieRenderer.func_225623_a_(WixieRenderer.java:15) ~[ars_nouveau:1.17] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] 
```

Using `geckolib-forge-1.16.5-3.0.36` (and `ars_nouveau-1.16.5-1.17` if that matters)

**Comment by AzureDoom** [comment]
would best be reported to the ars dev.
