### ISSUE TITLE
1.12.2 Exceptions Reading Molang

### ISSUE THREAD

**Issue by BlackJar72** [bernie-g/geckolib#147]
This gets thrown, over and over, during initialization:

19:14:51] [Client thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Dungeon Mobs, FMLFileResourcePack:Doomlike Dungeons, FMLFileResourcePack:Thaumcraft, FMLFileResourcePack:Baubles, FMLFileResourcePack:GeckoLib
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: java.lang.IndexOutOfBoundsException: Index: -1, Size: 4
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at java.util.ArrayList$SubList.rangeCheck(ArrayList.java:1227)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at java.util.ArrayList$SubList.get(ArrayList.java:1044)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:332)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:334)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseSymbolsMolang(MolangParser.java:232)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseOneLine(MolangParser.java:217)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseExpression(MolangParser.java:158)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseJson(MolangParser.java:119)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:185)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:51)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToKeyFrames(JsonKeyFrameUtils.java:162)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:280)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:36)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.geckolib3.resource.GeckoLibCache.onResourceManagerReload(GeckoLibCache.java:99)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.notifyReloadListeners(SimpleReloadableResourceManager.java:132)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.reloadResources(SimpleReloadableResourceManager.java:112)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.client.Minecraft.refreshResources(Minecraft.java:869)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.client.Minecraft.init(Minecraft.java:514)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:422)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.client.main.Main.main(Main.java:118)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at GradleStart.main(GradleStart.java:25)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: java.lang.IndexOutOfBoundsException: Index: -1, Size: 4
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at java.util.ArrayList$SubList.rangeCheck(ArrayList.java:1227)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at java.util.ArrayList$SubList.get(ArrayList.java:1044)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:332)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:334)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseSymbolsMolang(MolangParser.java:232)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseOneLine(MolangParser.java:217)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseExpression(MolangParser.java:158)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseJson(MolangParser.java:119)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:185)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:51)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToKeyFrames(JsonKeyFrameUtils.java:162)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:280)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:36)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at software.bernie.geckolib3.resource.GeckoLibCache.onResourceManagerReload(GeckoLibCache.java:99)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.notifyReloadListeners(SimpleReloadableResourceManager.java:132)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.client.resources.SimpleReloadableResourceManager.reloadResources(SimpleReloadableResourceManager.java:112)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.client.Minecraft.refreshResources(Minecraft.java:869)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.client.Minecraft.init(Minecraft.java:514)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.client.Minecraft.run(Minecraft.java:422)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.client.main.Main.main(Main.java:118)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: 	at GradleStart.main(GradleStart.java:25)
[19:14:51] [Client thread/INFO] [STDERR]: [software.bernie.shadowed.eliotlash.molang.MolangParser:parseSymbolsMolang:236]: java.lang.IndexOutOfBoundsException: Index: -1, Size: 4

As a side note, I also get an error before this for 
"[19:14:51] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: geckolib3:geo/wolf_armor.geo.json" which probably isn't related but I thought I'd bring it up.

I later gett a crash when checking the animation status or current animation, possibly actually related.

**Comment by AzureDoom** [comment]
1.12.2 is honestly out of support, unless Gecko himself fixes but I wouldn't hold out for it.
