### ISSUE TITLE
1.17 Fabric Crash when using F3 + T to reload assets

### ISSUE THREAD

**Issue by RacoonDog** [bernie-g/geckolib#151]
Game crashes after using F3 + T to reload assets

May not be linked with F3+T since I wasn't capable of replicating the crash, but it happened after using the combo

```
[01:40:39] [Render thread/FATAL] (Minecraft) Reported exception thrown!
 net.minecraft.util.crash.CrashException: Rendering entity in world
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:166) ~[minecraft-1.17-mapped-net.fabricmc.yarn-1.17+build.13-v2.jar:?]
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer.java:1483) ~[minecraft-1.17-mapped-net.fabricmc.yarn-1.17+build.13-v2.jar:?]
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1231) ~[minecraft-1.17-mapped-net.fabricmc.yarn-1.17+build.13-v2.jar:?]
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1001) ~[minecraft-1.17-mapped-net.fabricmc.yarn-1.17+build.13-v2.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:806) ~[minecraft-1.17-mapped-net.fabricmc.yarn-1.17+build.13-v2.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1114) ~[minecraft-1.17-mapped-net.fabricmc.yarn-1.17+build.13-v2.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:730) [minecraft-1.17-mapped-net.fabricmc.yarn-1.17+build.13-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [minecraft-1.17-mapped-net.fabricmc.yarn-1.17+build.13-v2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NullPointerException: Cannot read field "locals" because "this.currentStatement" is null
	at software.bernie.shadowed.eliotlash.molang.MolangParser.getVariable(MolangParser.java:87) ~[geckolib-fabric-1.17-3.0.8-dev.jar:?]
	at software.bernie.shadowed.eliotlash.molang.MolangParser.setValue(MolangParser.java:73) ~[geckolib-fabric-1.17-3.0.8-dev.jar:?]
	at software.bernie.geckolib3.model.AnimatedGeoModel.setMolangQueries(AnimatedGeoModel.java:127) ~[geckolib-fabric-1.17-3.0.8-dev.jar:?]
	at software.bernie.geckolib3.core.processor.AnimationProcessor.preAnimationSetup(AnimationProcessor.java:296) ~[geckolib-fabric-1.17-3.0.8-dev.jar:?]
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:76) ~[geckolib-fabric-1.17-3.0.8-dev.jar:?]
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:30) ~[geckolib-fabric-1.17-3.0.8-dev.jar:?]
	at software.bernie.geckolib3.renderers.geo.GeoReplacedEntityRenderer.render(GeoReplacedEntityRenderer.java:144) ~[geckolib-fabric-1.17-3.0.8-dev.jar:?]
	at software.bernie.geckolib3.renderers.geo.GeoReplacedEntityRenderer.render(GeoReplacedEntityRenderer.java:72) ~[geckolib-fabric-1.17-3.0.8-dev.jar:?]
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:135) ~[minecraft-1.17-mapped-net.fabricmc.yarn-1.17+build.13-v2.jar:?]
	... 15 more
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2021-07-01, 1:40 a.m.
Description: Rendering entity in world

java.lang.NullPointerException: Cannot read field "locals" because "this.currentStatement" is null
	at software.bernie.shadowed.eliotlash.molang.MolangParser.getVariable(MolangParser.java:87)
	at software.bernie.shadowed.eliotlash.molang.MolangParser.setValue(MolangParser.java:73)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setMolangQueries(AnimatedGeoModel.java:127)
	at software.bernie.geckolib3.core.processor.AnimationProcessor.preAnimationSetup(AnimationProcessor.java:296)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:76)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:30)
	at software.bernie.geckolib3.renderers.geo.GeoReplacedEntityRenderer.render(GeoReplacedEntityRenderer.java:144)
	at software.bernie.geckolib3.renderers.geo.GeoReplacedEntityRenderer.render(GeoReplacedEntityRenderer.java:72)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:135)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer.java:1483)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1231)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1001)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:806)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1114)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at software.bernie.shadowed.eliotlash.molang.MolangParser.getVariable(MolangParser.java:87)
	at software.bernie.shadowed.eliotlash.molang.MolangParser.setValue(MolangParser.java:73)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setMolangQueries(AnimatedGeoModel.java:127)
	at software.bernie.geckolib3.core.processor.AnimationProcessor.preAnimationSetup(AnimationProcessor.java:296)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:76)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:30)
	at software.bernie.geckolib3.renderers.geo.GeoReplacedEntityRenderer.render(GeoReplacedEntityRenderer.java:144)
	at software.bernie.geckolib3.renderers.geo.GeoReplacedEntityRenderer.render(GeoReplacedEntityRenderer.java:72)

-- Entity being rendered --
Details:
	Entity Type: minecraft:creeper (net.minecraft.entity.mob.CreeperEntity)
	Entity ID: 2934
	Entity Name: Creeper
	Entity's Exact location: 157.50, 40.00, -219.50
	Entity's Block location: World: (157,40,-220), Section: (at 13,8,4 in 9,2,-14; chunk contains blocks 144,0,-224 to 159,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null

-- Renderer details --
Details:
	Assigned renderer: software.bernie.example.client.renderer.entity.ReplacedCreeperRenderer@712de3ff
	Location: -45.65,-25.62,45.31 - World: (-46,-26,45), Section: (at 2,6,13 in -3,-2,2; chunk contains blocks -48,0,32 to -33,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: 16.875
	Delta: 0.56000024
Stacktrace:
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:135)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer.java:1483)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1231)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1001)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Player693'/160, l='ClientLevel', x=203.15, y=64.00, z=-264.81]]
	Chunk stats: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (208,74,-256), Section: (at 0,10,0 in 13,4,-16; chunk contains blocks 208,0,-256 to 223,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 18675 game time, 18675 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:370)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2399)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:749)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: No
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 749230160 bytes (714 MiB) / 2566914048 bytes (2448 MiB) up to 6417285120 bytes (6120 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD FX(tm)-6300 Six-Core Processor             
	Identifier: AuthenticAMD Family 21 Model 2 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 3
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1060 3GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 3072.00
	Graphics card #0 deviceId: 0x1c02
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6677
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.07
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.07
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 1.07
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.07
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 31473.36
	Virtual memory used (MB): 23685.94
	Swap memory total (MB): 6996.50
	Swap memory used (MB): 439.91
	JVM Flags: 1 total; -XX:+ShowCodeDetailsInExceptionMessages
	Fabric Mods: 
		chaosawakens: ChaosAwakens 1.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c3d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.6
		geckolib3: Geckolib 3.0.8
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17
		modmenu: Mod Menu 2.0.0-beta.7
	Launched Version: Fabric
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 466.77, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
	Player Count: 1 / 8; [ServerPlayerEntity['Player693'/160, l='ServerLevel[New World]', x=203.15, y=64.00, z=-264.81]]
	Data Packs: vanilla (incompatible), Fabric Mods
```

**Comment by AzureDoom** [comment]
yeah it's a 1 out of 100 crash when reloading, it just happens and we can't figure out why sadly
