### ISSUE TITLE
Function can't be found

### ISSUE THREAD

**Issue by red2blue** [bernie-g/geckolib#170]
latest 1.17.1 latest geckolib

[18:27:27] [Worker-Main-8/INFO]: [STDERR]: java.lang.Exception: Function '1math.sin' couldn't be found!
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:474)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:286)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:334)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseSymbolsMolang(MolangParser.java:232)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseOneLine(MolangParser.java:217)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseExpression(MolangParser.java:158)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseJson(MolangParser.java:119)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:180)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:54)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:174)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:293)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:31)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:67)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:86)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: java.lang.Exception: Function '1math.sin' couldn't be found!
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:474)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:286)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:334)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseSymbolsMolang(MolangParser.java:232)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseOneLine(MolangParser.java:217)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseExpression(MolangParser.java:158)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseJson(MolangParser.java:119)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:180)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:54)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:174)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:293)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:31)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:67)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:86)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[18:27:27] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by bernie-g** [comment]
Read the error? Your molang is invalid.

**Comment by red2blue** [comment]
The fuck is a molang?

**Comment by red2blue** [comment]
"its molang" "even though you have no idea what molang, I won't tell you and close the ticket, mwahaaha" 

Not sure how a Mojang component can be invalid if  its literally straight from mojang.

**Comment by bernie-g** [comment]
Read the wiki, it explains it in great detail.
