### ISSUE TITLE
[Forge 1.16.5]Crash when used with Epic fight mod 5.1.1

### ISSUE THREAD

**Issue by HEYMANCXN** [bernie-g/geckolib#187]
Got something error when I used Epic Fight with Geckolib 1.16.5 3.0.46
Here's my crash report:
java.lang.NullPointerException: Rendering overlay
at software.bernie.geckolib3.util.json.JsonAnimationUtils.getObjectListAsArray(JsonAnimationUtils.java:187) ~[?:3.0.46] {re:classloading}
at software.bernie.geckolib3.util.json.JsonAnimationUtils.getAnimations(JsonAnimationUtils.java:36) ~[?:3.0.46] {re:classloading}
at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:26) ~[?:3.0.46] {re:classloading}
at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:70) ~[?:3.0.46] {re:classloading}
at software.bernie.geckolib3.resource.GeckoLibCache$$Lambda$4265/630313530.apply(Unknown Source) ~[?:?] {}
at software.bernie.geckolib3.resource.GeckoLibCache.lambda$null$5(GeckoLibCache.java:88) ~[?:3.0.46] {re:classloading}
at software.bernie.geckolib3.resource.GeckoLibCache$$Lambda$4376/419108399.get(Unknown Source) ~[?:?] {}
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51] {}
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

**Comment by AzureDoom** [comment]
https://github.com/Yesssssman/epicfightmod/issues/593#issuecomment-938458522

Issue is on Epic Fights side, they will need to use a different folder name for their animations

**Comment by AzureDoom** [comment]
already did
