### ISSUE TITLE
Reflection InvocationTargetException

### ISSUE THREAD

**Issue by NerjalNosk** [bernie-g/geckolib#219]
I just wanted to notify an exception I've got while reading my logs.
It didn't cause any issue (at least none that I know of), but it did appear here, so I thought it might be interesting.
Running on Mc 1.18.1 with Fabric modloader 0.12.12-1.18.1

```
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:500)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:286)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseSymbolsMolang(MolangParser.java:232)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseOneLine(MolangParser.java:217)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseExpression(MolangParser.java:158)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseJson(MolangParser.java:119)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:180)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:55)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToKeyFrames(JsonKeyFrameUtils.java:159)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:284)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:31)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:67)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:86)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: Caused by: java.lang.Exception: Function 'null' requires at least 3 arguments. 1 are given!
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.functions.Function.<init>(Function.java:22)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.functions.utility.Lerp.<init>(Lerp.java:11)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	... 25 more
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: java.lang.reflect.InvocationTargetException
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:500)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:286)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseSymbolsMolang(MolangParser.java:232)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseOneLine(MolangParser.java:217)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseExpression(MolangParser.java:158)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.molang.MolangParser.parseJson(MolangParser.java:119)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:180)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:55)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToKeyFrames(JsonKeyFrameUtils.java:159)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:284)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:31)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:67)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:86)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: Caused by: java.lang.Exception: Function 'null' requires at least 3 arguments. 1 are given!
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.functions.Function.<init>(Function.java:22)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	at software.bernie.shadowed.eliotlash.mclib.math.functions.utility.Lerp.<init>(Lerp.java:11)
[13:47:31] [Worker-Main-1/INFO]: [STDERR]: 	... 25 more
```

**Comment by finallion** [comment]
Can confirm. Happening with the 3.0.25 fabric version - with and without other mods.
https://pastebin.com/SDksGqJq

**Comment by AzureDoom** [comment]
This is just due to an animation file using the wrong math, this doesn't affect anything that would stop a world from loading. Works either way but a fix will come to quiet this message as it's a non-issue.
