### ISSUE TITLE
Crash when reloading Resource Packs

### ISSUE THREAD

**Issue by spoorn** [bernie-g/geckolib#237]
I saw this has been happening since last year: https://github.com/bernie-g/geckolib/issues/151

Except it's not 1 out of 100, I can reproduce this pretty often (it's almost like half or a third of the time).

This is for
Minecraft 1.18.2
Fabric Loader 0.13.3
Geckolib3 3.0.36

Crashes with that error when reloading resource packs:

```
java.lang.NullPointerException: Cannot read field "locals" because "this.currentStatement" is null
	at software.bernie.shadowed.eliotlash.molang.MolangParser.getVariable(MolangParser.java:87)
	at software.bernie.shadowed.eliotlash.molang.MolangParser.setValue(MolangParser.java:73)
	at software.bernie.geckolib3.core.controller.AnimationController.setAnimTime(AnimationController.java:499)
	at software.bernie.geckolib3.core.controller.AnimationController.processCurrentAnimation(AnimationController.java:562)
	at software.bernie.geckolib3.core.controller.AnimationController.process(AnimationController.java:493)
	at software.bernie.geckolib3.core.processor.AnimationProcessor.tickAnimation(AnimationProcessor.java:71)
	at software.bernie.geckolib3.model.AnimatedGeoModel.setLivingAnimations(AnimatedGeoModel.java:75)
	at com.yahoo.chirpycricket.wildlife.client.model.AnimatedLivingEntityModel.setLivingAnimations(AnimatedLivingEntityModel.java:40)
	at com.yahoo.chirpycricket.wildlife.client.model.AnimatedLivingEntityModel.setLivingAnimations(AnimatedLivingEntityModel.java:13)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:154)
	at com.yahoo.chirpycricket.wildlife.client.entity.WildlifeRenderer.render(WildlifeRenderer.java:30)
	at com.yahoo.chirpycricket.wildlife.client.entity.WildlifeRenderer.method_3936(WildlifeRenderer.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1563)
	at net.minecraft.class_761.method_22710(class_761.java:1311)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by AzureDoom** [comment]
Ensure your animations are correct, this is an error stating your having issues in your animations using molang.
