### ISSUE TITLE
Server crash at startup: BipedModel class not found

### ISSUE THREAD

**Issue by GoForceX** [bernie-g/geckolib#257]
# Info
Mod File: geckolib-forge-1.16.5-3.0.72.jar
Failure message: GeckoLib (geckolib3) has failed to load correctly
java.lang.RuntimeException: Cannot find class net/minecraft/client/renderer/entity/model/BipedModel
Mod Version: 3.0.72
Mod Issue URL: https://github.com/bernie-g/geckolib/issues
Exception message: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.model.BipedModel

# Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:718) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.forName0(Native Method) ~[?:?] {}
	at java.lang.Class.forName(Class.java:467) ~[?:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchyFromFile(TransformerClassWriter.java:157) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:112) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.access$100(TransformerClassWriter.java:34) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:177) ~[modlauncher-8.1.3.jar:?] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:372) ~[asm-tree-9.1.jar:9.1] {}
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:99) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:59) ~[modlauncher-8.1.3.jar:?] {}
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202) ~[asm-9.1.jar:9.1] {}
	at org.objectweb.asm.Frame.merge(Frame.java:1299) ~[asm-9.1.jar:9.1] {}
	at org.objectweb.asm.Frame.merge(Frame.java:1244) ~[asm-9.1.jar:9.1] {}
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610) ~[asm-9.1.jar:9.1] {}
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546) ~[asm-9.1.jar:9.1] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769) ~[asm-tree-9.1.jar:9.1] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649) ~[asm-tree-9.1.jar:9.1] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452) ~[asm-tree-9.1.jar:9.1] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.forName0(Native Method) ~[?:?] {}
	at java.lang.Class.forName(Class.java:467) ~[?:?] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by AzureDoom** [comment]
Closed with https://github.com/bernie-g/geckolib/commit/2b58f373420a8763462f291aab3ade60afb1d939
