### ISSUE TITLE
Render Overlay Crash

### ISSUE THREAD

**Issue by DayanSon** [bernie-g/geckolib#292]
I talked to the other mods Developer and they said his animations and Geko are using the same path to store animation but geko is not ignoring files that are not geko based in the same directory.
This is a crash between Gekolib and Gun's RPG mod (https://www.curseforge.com/minecraft/mc-mods/guns-rpg)

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/6/22 4:53 AM
Description: Rendering overlay

java.lang.NullPointerException: Rendering overlay
at software.bernie.geckolib3.util.json.JsonAnimationUtils.getObjectListAsArray(JsonAnimationUtils.java:198) ~[?:3.0.89] {re:classloading}
at software.bernie.geckolib3.util.json.JsonAnimationUtils.getAnimations(JsonAnimationUtils.java:47) ~[?:3.0.89] {re:classloading}
at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:27) ~[?:3.0.89] {re:classloading}
at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:70) ~[?:3.0.89] {re:classloading}
at software.bernie.geckolib3.resource.GeckoLibCache$$Lambda$21859/598599045.apply(Unknown Source) ~[?:?] {}
at software.bernie.geckolib3.resource.GeckoLibCache.lambda$null$5(GeckoLibCache.java:88) ~[?:3.0.89] {re:classloading}
at software.bernie.geckolib3.resource.GeckoLibCache$$Lambda$22003/2145842718.get(Unknown Source) ~[?:?] {}
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51] {}
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Render thread
Stacktrace:
at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:484) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:magnesium.mixins.json:core.matrix.MixinGameRenderer,pl:mixin:APP:magnesium_extras.mixins.json:TotalDarkness.MixinGameRenderer,pl:mixin:APP:magnesium_extras.mixins.json:Zoom.GameRendererMixin,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:484) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:magnesium.mixins.json:core.matrix.MixinGameRenderer,pl:mixin:APP:magnesium_extras.mixins.json:TotalDarkness.MixinGameRenderer,pl:mixin:APP:magnesium_extras.mixins.json:Zoom.GameRendererMixin,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$501/1160278903.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

-- System Details --
Details:
Minecraft Version: 1.16.5
Minecraft Version ID: 1.16.5
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1010910920 bytes (964 MB) / 3424649216 bytes (3266 MB) up to 6561988608 bytes (6258 MB)
CPUs: 12
JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7040m -Xms256m
ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
ModLauncher launch target: fmlclient
ModLauncher naming: srg
ModLauncher services:
/mixin-0.8.4.jar mixin PLUGINSERVICE
/eventbus-4.0.0.jar eventbus PLUGINSERVICE
/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE
/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE
/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE
/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE
/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE
/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE
/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE
FML: 36.2
Forge: net.minecraftforge:36.2.34
FML Language Providers:
javafml@36.2
minecraft@1
Mod List:

(long list of mods let me know if you need that list) 

Crash Report UUID: b632a14e-2f12-4332-aee0-ac61e6a55420
	RoadRunner != Lithium: This instance was launched using RoadRunner, which is an *unofficial* Lithium fork! Please **do not** report bugs to them!
	Launched Version: forge-36.2.34
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.95, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 5600G with Radeon Graphics

**Comment by AzureDoom** [comment]
Nothing something on our end to fix.

**Comment by DayanSon** [comment]
This is such an odd conflict. is the geko mod over writing the files in that "folder" or looking for it.
