### ISSUE TITLE
Server crash with latest version

### ISSUE THREAD

**Issue by gamerpotion** [bernie-g/geckolib#301]
Hi,
Im using this on my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg
for version geckolib-fabric-1.19-3.1.21.jar  on our official server,  people are getting constant crashes and unable to login afterwards

an emample of a crash I experienced is below.  (when i reverted back to old version the crash doesnt happen)

```---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2022-10-04 01:59:47
Description: Rendering entity in world

java.lang.AbstractMethodError: Receiver class net.barribob.boss.mob.utils.SimpleLivingGeoRenderer$GeoRenderer does not define or inherit an implementation of the resolved method 'abstract void setCurrentRTB(net.minecraft.class_4597)' of interface software.bernie.geckolib3.renderers.geo.IGeoRenderer.
	at software.bernie.geckolib3.renderers.geo.IGeoRenderer.render(IGeoRenderer.java:34)
	at net.barribob.boss.mob.utils.SimpleLivingGeoRenderer.render(SimpleLivingGeoRenderer.kt:111)
	at net.barribob.boss.mob.utils.SimpleLivingGeoRenderer.render(SimpleLivingGeoRenderer.kt:25)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:183)
	at net.barribob.boss.mob.utils.SimpleLivingGeoRenderer.render(SimpleLivingGeoRenderer.kt:90)
	at net.barribob.boss.mob.utils.SimpleLivingGeoRenderer.method_3936(SimpleLivingGeoRenderer.kt:25)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at software.bernie.geckolib3.renderers.geo.IGeoRenderer.render(IGeoRenderer.java:34)
	at net.barribob.boss.mob.utils.SimpleLivingGeoRenderer.render(SimpleLivingGeoRenderer.kt:111)
	at net.barribob.boss.mob.utils.SimpleLivingGeoRenderer.render(SimpleLivingGeoRenderer.kt:25)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:183)
	at net.barribob.boss.mob.utils.SimpleLivingGeoRenderer.render(SimpleLivingGeoRenderer.kt:90)
	at net.barribob.boss.mob.utils.SimpleLivingGeoRenderer.method_3936(SimpleLivingGeoRenderer.kt:25)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Entity being rendered --
Details:
	Entity Type: bosses_of_mass_destruction:obsidilith (net.barribob.boss.mob.mobs.obsidilith.ObsidilithEntity)
	Entity ID: 18101
	Entity Name: Welcome To Spawn! -❤Soul❤-
	Entity's Exact location: -121.47, 60.00, -32.32
	Entity's Block location: World: (-122,60,-33), Section: (at 6,12,15 in -8,3,-3; chunk contains blocks -128,-64,-48 to -113,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.barribob.boss.mob.utils.SimpleLivingGeoRenderer@7f2552bc
	Location: 28.03,-9.65,-12.82 - World: (28,-10,-13), Section: (at 12,6,3 in 1,-1,-1; chunk contains blocks 16,-64,-16 to 31,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Rotation: 0.0
	Delta: 0.50007546
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 2 total; [class_746['JDKun11'/12365, l='ClientLevel', x=-149.50, y=69.00, z=-19.50], class_745['SoulVI'/17993, l='ClientLevel', x=-141.62, y=70.19, z=-13.84]]
	Chunk stats: 1024, 251
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,0), Section: (at 0,7,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 87464038 game time, 10576274 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
	pehkui:debug/render/entity: bosses_of_mass_destruction:obsidilith
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by AzureDoom** [comment]
You will need to report to Boss of Mass Destruction as they need to update their code to the new update
