### ISSUE TITLE
[1.19.2] Index out of bounds exception

### ISSUE THREAD

**Issue by enimog** [bernie-g/geckolib#366]
Hi,

I see a bunch of these error in my logs. I'm not sure if they cause an issue or not, but I thought it would be good to report them;

```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList$SubList.get(ArrayList.java:1149)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:306)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:282)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:439)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:266)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:308)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:283)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.geckolib3.core.molang.MolangParser.parseSymbolsMolang(MolangParser.java:228)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.geckolib3.core.molang.MolangParser.parseOneLine(MolangParser.java:216)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.geckolib3.core.molang.MolangParser.parseExpression(MolangParser.java:174)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.geckolib3.core.molang.MolangParser.parseJson(MolangParser.java:154)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:177)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:55)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:171)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:267)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:30)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:72)
	at TRANSFORMER/geckolib3@3.1.39/software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:90)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by AzureDoom** [comment]
Non-issue, safe to ignore
