### ISSUE TITLE
(Fabric/1.19.3) keeps crashing when i open the game

### ISSUE THREAD

**Issue by Lonelyme321** [bernie-g/geckolib#374]
Geckolib seems to crash the game and when I remove it then it works properly.

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-01-04 00:09:46
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'hwg'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$cpk000$catchFabricInit(class_310.java:15480)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.RuntimeException: Mixin transformation of software.bernie.geckolib.renderer.GeoEntityRenderer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at mod.azure.hwg.client.ClientInit.onInitializeClient(ClientInit.java:36)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 27 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [enchancement.mixins.json:frostbite.client.integration.geckolib.GeoEntityRendererMixin from mod enchancement] from phase [DEFAULT] in config [enchancement.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 30 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on enchancement$frostbite could not find any targets matching 'getTexture' in software.bernie.geckolib.renderer.GeoEntityRenderer. Using refmap enchancement-refmap.json [PREINJECT Applicator Phase -> enchancement.mixins.json:frostbite.client.integration.geckolib.GeoEntityRendererMixin from mod enchancement -> Prepare Injections ->  -> handler$bhh001$enchancement$frostbite(Lnet/minecraft/class_1297;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.5)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at mod.azure.hwg.client.ClientInit.onInitializeClient(ClientInit.java:36)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.client.MinecraftClient.redirect$cpk000$catchFabricInit(MinecraftClient:15480)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:465)
	at net.minecraft.client.main.Main.main(Main:205)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
Mixins in Stacktrace: None found

-- Initialization --
Details:
Stacktrace:
	at fudge.notenoughcrashes.mixinhandlers.EntryPointCatcher.handleEntryPointError(EntryPointCatcher.java:28)
	at net.minecraft.class_310.redirect$cpk000$catchFabricInit(class_310.java:15482)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Mixins in Stacktrace:
	net.minecraft.class_310:
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		net.bettercombat.mixin.client.MinecraftClientAccessor (bettercombat.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (sodium.mixins.json)
		fudge.notenoughcrashes.mixins.client.MixinMinecraftClient (notenoughcrashes.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
		moriyashiine.enchancement.mixin.vanillachanges.cooldownpreventsusage.client.MinecraftClientMixin (enchancement.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		com.natamus.collective_fabric.fabric.mixin.MinecraftMixin (collective_fabric.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		ca.fxco.memoryleakfix.mixin.targetEntityLeak.MinecraftClient_targetClearMixin (memoryleakfix.mixins.json)
		dev.tr7zw.itemswapper.mixin.MinecraftMixin (itemswapper.mixins.json)
		org.betterx.betternether.mixin.client.MinecraftClientMixin (betternether.mixins.client.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		net.bettercombat.mixin.client.MinecraftClientInject (bettercombat.mixins.json)
		moriyashiine.enchancement.mixin.perception.client.MinecraftClientMixin (enchancement.mixins.json)
		ca.fxco.memoryleakfix.mixin.customPayloadLeak.MinecraftClient_freeBufferMixin (memoryleakfix.mixins.json)
		ca.fxco.memoryleakfix.mixin.hugeScreenshotLeak.MinecraftClient_screenshotMixin (memoryleakfix.mixins.json)
		net.darkhax.bookshelf.mixin.client.AccessorMinecraft (bookshelf.common.mixins.json)
		me.ramidzkh.fabrishot.mixins.MinecraftClientMixin (mixins.fabrishot.json)
		io.github.jamalam360.utility.belt.mixin.client.MinecraftClientMixin (utilitybelt.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		dev.isxander.zoomify.mixins.hooks.MinecraftClientMixin (zoomify.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		org.betterx.bclib.mixin.client.MinecraftMixin (bclib.mixins.client.json)
		me.roundaround.roundalib.mixin.MinecraftClientMixin (roundalib.mixins.json)
		net.combatroll.mixin.MinecraftClientMixin (combatroll.mixins.json)
		fudge.notenoughcrashes.fabric.mixins.client.CatchInitMInecraftClientMixin (notenoughcrashes.fabric.mixins.json)
		com.aizistral.nochatreports.mixins.client.MixinMinecraft (nochatreports.mixins.json)
		io.wispforest.owo.mixin.MinecraftClientMixin (owo.mixins.json)
		io.wispforest.owo.mixin.ui.MinecraftClientMixin (owo.mixins.json)
		squeek.appleskin.mixin.MinecraftClientMixin (appleskin.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
	net.minecraft.client.main.Main:
		fudge.notenoughcrashes.fabric.mixins.client.MixinMain (notenoughcrashes.fabric.mixins.json)
		ca.fxco.memoryleakfix.mixin.spongePoweredLeak.Main_clientLoadedMixin (memoryleakfix.mixins.json)
		io.github.ultimateboomer.smoothboot.mixin.client.MainMixin (smoothboot.mixins.json)

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 19.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 236700160 bytes (225 MiB) / 759169024 bytes (724 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 11
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e91
	Graphics card #0 versionInfo: DriverVersion=30.0.100.9805
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 20964.89
	Virtual memory used (MB): 16639.50
	Swap memory total (MB): 12909.59
	Swap memory used (MB): 2473.82
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		advancednetherite: Advanced Netherite 1.6.6-1.19.3
		advancementinfo: AdvancementInfo 1.19.3-fabric0.68.1-1.3.1
		antighost: AntiGhost 1.19.3-fabric0.68.1-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		appleskin: AppleSkin 2.4.2+mc1.19.3
		architectury: Architectury 7.0.66
		bclib: BCLib 2.2.3
		bettercombat: Better Combat 1.5.3+1.19.3
		betterf3: BetterF3 5.0.0
		bettermounthud: Better Mount HUD 1.2.1
		betternether: Better Nether 8.1.2
		blockus: Blockus 2.6.1+1.19.3
			terraform-wood-api-v1: Terraform Wood API (v1) 5.0.0-beta.1
		bookshelf: Bookshelf 17.0.2
		borderlessmining: Borderless Mining 1.1.6+1.19.3
		capybara: Capybara 2.0.1
		cardinal-components: Cardinal Components API 5.1.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-block: Cardinal Components API (blocks) 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 5.45
			fiber: fiber 0.23.0-2
		combatroll: Combat Roll 1.1.1+1.19.3
		copper-horns: Return Copper Horns 1.0.1
		cullleaves: Cull Leaves 3.0.2
			midnightlib: MidnightLib 1.1.0
		customizableelytra: Customizable Elytra 1.6.5-1.19.3
		debugify: Debugify 1.19.3+1.1
			com_github_llamalad7_mixinextras: mixinextras 0.1.1
		delightful-froge: Delightful Froge 0.1.0+1.19.3
		dungeon_difficulty: Dungeon Difficulty 1.2.1+1.19.3
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.1.1
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		enchancement: Enchancement 1.19-9
			step-height-entity-attribute: Step Height Entity Attribute 1.1.0
		enchdesc: EnchantmentDescriptions 14.0.4
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19.3
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		esr: Emissive Skin Renderer 3.0.2
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.5
		fabric-api: Fabric API 0.71.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.0+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.29+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.10+99f9db8085
			fabric-command-api-v1: Fabric Command API (v1) 1.2.20+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.1.16+99f9db8085
			fabric-commands-v0: Fabric Commands (v0) 0.2.37+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.46+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.3+87855a7085
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.39+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.41+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.7+e498f5f085
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.10+0a2a0d0b85
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.30+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.28+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.26+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.16+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.33+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.3.0+85f102ee85
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.3+2608564685
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.0+9f179aa185
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+9f179aa185
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.29+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.32+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+6dc0edd785
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.1+280be3ab85
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.40+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.12+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.7+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.13+f1e4495b85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.0+5b9a588b85
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.12
		fabricskyboxes: FabricSkyBoxes 0.6.1+mc1.19.3
		fabrictailor: Fabric Tailor 2.0.2
			config2brigadier: Config to Brigadier 1.2.1
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabrishot: Fabrishot 1.9.1
		ferritecore: FerriteCore 5.1.0
		fsb-interop: FabricSkyBoxes Interop 1.1.3+mc1.19.3-build.26
		fwaystones: Fabric Waystones 3.0.6+mc1.19.3
		geckolib: Geckolib 4.0.3
			com_eliotlash_mclib_mclib: mclib 20
		holdthatchunk: Hold That Chunk 2.0.1
		hwg: Happiness is a Warm Gun 1.3.1
		incantationem: Incantationem 1.2+1.19.3
		itemswapper: ItemSwapper 0.3.2-mc1.19.3
		jamlib: JamLib 0.5.2
		java: OpenJDK 64-Bit Server VM 19
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.10.4
		manic_mr: Manic 1.0.1
		memoryleakfix: memory Leak Fix 1.19.3-0.7.0
		minecraft: Minecraft 1.19.3
		mixin-conflict-helper: Mixin Conflict Helper 1.2.0
		mixintrace: MixinTrace 1.1.1+1.17
		modmenu: Mod Menu 5.0.2
		morechathistory: MoreChatHistory 1.1.1
		mousetweaks: Mouse Tweaks 2.24
		nochatreports: No Chat Reports 1.19.3-v1.19.0
		nofade: No Fade 1.18-2.0.1
		notenoughcrashes: Not Enough Crashes 4.2.0+1.19.3
		optigui: OptiGUI 1.1.6
			org_apache_commons_commons-text: commons-text 1.9
		owo: oωo 0.9.3+1.19.3
			blue_endless_jankson: jankson 1.2.1
		pigsteel: Pigsteel Mod 1.8.1
		player-animator: Player Animator 0.4.1+1.19.3
		plushies: Plushie Mod 1.2.1
		projectile_damage: Projectile Damage Attribute 3.0.0+1.19.3
		qu-enchantments: Qu Enchantments 1.3.1-1.19
			mm: Manningham Mills 2.3
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		respawnablepets: Respawnable Pets 1.19-3
		roughlyenoughitems: Roughly Enough Items 10.0.581
			error_notifier: Error Notifier 1.0.9
		sanguine_mr: Sanguine 0.3.0
		simple_backpack: SimpleBackpack 1.4.7
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.3
		smoothboot: Smooth Boot 1.19-1.7.1
		snowballsfreezemobs-fabric: Snowballs Freeze Mobs (Fabric) 2.3
		sodium: Sodium 0.4.6+build.20
		sodium-extra: Sodium Extra 0.4.14+mc1.19.3-build.81
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		stackables: Stackables 1.0.0
			roundalib: RoundaLib 0.2.1
		starlight: Starlight 1.1.1+fabric.ae22326
		tooltipfix: ToolTip Fix 1.1.1-1.19.3
		transcendingtrident-fabric: Transcending Trident (Fabric) 3.0
		trinkets: Trinkets 3.5.0
		utilitybelt: Utility Belt 1.2.1
		visuality: Visuality 0.6.0
		worldedit: WorldEdit 7.2.13+46576cc
		yet-another-config-lib: YetAnotherConfigLib 2.1.1
		yosbr: YOSBR 0.1.1
		youritemsaresafe-fabric: Your Items Are Safe (Fabric) 2.2
		zoomify: Zoomify 2.9.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.6
	Launched Version: 1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Happiness is a Warm Gun (hwg), Not Enough Crashes (notenoughcrashes)
```

**Comment by AzureDoom** [comment]
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [enchancement.mixins.json:frostbite.client.integration.geckolib.GeoEntityRendererMixin from mod enchancement] from phase [DEFAULT] in config [enchancement.mixins.json] FAILED during APPLY
```
This is on enchancement, their mixin isn't working.
