### ISSUE TITLE
Game crashes everytime I enter a world.

### ISSUE THREAD

**Issue by Korogaline** [bernie-g/geckolib#379]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 18/01/23 23.27
Description: Unexpected error

java.lang.NoSuchMethodError: software.bernie.geckolib3.core.manager.AnimationData.getAnimationControllers()Ljava/util/HashMap;
	at com.hollingsworth.arsnouveau.common.entity.WildenStalker.startAnimation(WildenStalker.java:128) ~[?:1.25.7] {re:classloading}
	at com.hollingsworth.arsnouveau.common.network.PacketAnimEntity$Handler$1.run(PacketAnimEntity.java:49) ~[?:1.25.7] {re:classloading}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?] {re:classloading}
	at com.hollingsworth.arsnouveau.common.network.PacketAnimEntity$Handler.handle(PacketAnimEntity.java:42) ~[?:1.25.7] {re:classloading}
	at com.hollingsworth.arsnouveau.common.network.Networking$$Lambda$5812/1076665849.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$8403/732697339.accept(Unknown Source) ~[?:?] {}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?] {re:mixin,re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2965/1912769093.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2967/269973396.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3266/535290917.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$8391/1724408930.apply(Unknown Source) ~[?:?] {}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[?:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?] {re:mixin,xf:fml:xaerominimap:xaero_clientplaynethandler_cleanup,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlechunkdata,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientplaynethandler_cleanup,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlechunkdata,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil$$Lambda$8550/958363292.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$505/293326812.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.hollingsworth.arsnouveau.common.entity.WildenStalker.startAnimation(WildenStalker.java:128) ~[?:1.25.7] {re:classloading}
	at com.hollingsworth.arsnouveau.common.network.PacketAnimEntity$Handler$1.run(PacketAnimEntity.java:49) ~[?:1.25.7] {re:classloading}
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?] {re:classloading}
	at com.hollingsworth.arsnouveau.common.network.PacketAnimEntity$Handler.handle(PacketAnimEntity.java:42) ~[?:1.25.7] {re:classloading}
	at com.hollingsworth.arsnouveau.common.network.Networking$$Lambda$5812/1076665849.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$8403/732697339.accept(Unknown Source) ~[?:?] {}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?] {re:mixin,re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2965/1912769093.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2967/269973396.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3266/535290917.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$8391/1724408930.apply(Unknown Source) ~[?:?] {}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[?:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?] {re:mixin,xf:fml:xaerominimap:xaero_clientplaynethandler_cleanup,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlechunkdata,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientplaynethandler_cleanup,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlechunkdata,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil$$Lambda$8550/958363292.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Korogaline'/135, l='ClientLevel', x=246.01, y=134.00, z=-94.70]]
	Chunk stats: Client Chunk Cache: 841, 550
	Level dimension: minecraft:overworld
	Level spawn location: World: (224,135,-144), Chunk: (at 0,8,0 in 14,-9; contains blocks 224,0,-144 to 239,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 46962 game time, 46962 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$505/293326812.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3086728304 bytes (2943 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |DONE      |Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.16.5-3.15.13.560.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.15.13.560  |DONE      |Manifest: NOSIGNATURE
		ExplorersCompass-1.16.5-1.1.2-forge.jar           |Explorer's Compass            |explorerscompass              |1.16.5-1.1.2-forge  |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.153.jar                          |Just Enough Items             |jei                           |7.7.1.153           |DONE      |Manifest: NOSIGNATURE
		byg-1.3.5.jar                                     |Oh The Biomes You'll Go       |byg                           |1.3.4               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.128.jar         |Just Enough Resources         |jeresources                   |0.12.1.128          |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		MmmMmmMmmMmm-1.16.5-1.3.1.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.3.0               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.1      |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-16.0.13a.jar                       |Valhelsia Core                |valhelsia_core                |16.0.13a            |DONE      |Manifest: NOSIGNATURE
		forbidden_arcanus-16.2.3.jar                      |Forbidden & Arcanus           |forbidden_arcanus             |16.2.3              |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.17.12b.jar               |Supplementaries               |supplementaries               |0.17.12             |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.17.0_Forge_1.16.5.jar           |Xaero's Minimap               |xaerominimap                  |22.17.0             |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.16.5-1.25.7.jar                     |Ars Nouveau                   |ars_nouveau                   |1.25.7              |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.16.4-FORGE-1.4.2.jar                  |Croptopia                     |croptopia                     |1.4.2               |DONE      |Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.3.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.3               |DONE      |Manifest: NOSIGNATURE
		selene-1.16.5-1.9.0.jar                           |Selene                        |selene                        |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.5.0.jar                   |Storage Drawers               |storagedrawers                |8.5.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: aaf1a1e0-8f80-4758-8f36-81d25a55f0f8
	Patchouli open book context: n/a
	Launched Version: 1.16.5-forge-36.2.34
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics GL version 4.6.0 - Build 30.0.101.2079, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/[1.16+]+Mo's+Vibrancy+Pack+v2.1.zip (incompatible), file/Genshin+(Mond)+Music+Replacements+01.zip (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz

**Comment by AzureDoom** [comment]
This due to ars nouveau, not us.
