### ISSUE TITLE
Updated to the new gekoLib release from the other day and wont load

### ISSUE THREAD

**Issue by BedrockLegends** [bernie-g/geckolib#38]
Its having somekind of mod conflicted 

[09Nov2020 11:42:39.333] [main/DEBUG] [mixin/]: Processing prepare() for PlatformAgent[MixinPlatformAgentDefault:ContainerHandleModLauncher.Resource(appliedenergistics2-8.1.0.jar:C:\_gdl\instances\Monumental Experience\mods\appliedenergistics2-8.1.0.jar)]
[09Nov2020 11:42:39.334] [main/DEBUG] [mixin/]: Registering mixin config: appliedenergistics2.mixins.json
[09Nov2020 11:42:39.350] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config appliedenergistics2.mixins.json
[09Nov2020 11:42:39.351] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
[09Nov2020 11:42:39.351] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
[09Nov2020 11:42:39.351] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
[09Nov2020 11:42:39.351] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:263)
[09Nov2020 11:42:39.351] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:46)
[09Nov2020 11:42:39.351] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:122)
[09Nov2020 11:42:39.351] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:145)
[09Nov2020 11:42:39.351] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:135)
[09Nov2020 11:42:39.351] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addNestedContainers(MixinPlatformManager.java:153)
[09Nov2020 11:42:39.351] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanForContainers(MixinPlatformManager.java:214)
[09Nov2020 11:42:39.352] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:187)
[09Nov2020 11:42:39.352] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190)
[09Nov2020 11:42:39.352] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:196)
[09Nov2020 11:42:39.352] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[09Nov2020 11:42:39.352] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at java.base/java.util.HashMap.forEach(HashMap.java:1425)
[09Nov2020 11:42:39.352] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[09Nov2020 11:42:39.352] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[09Nov2020 11:42:39.352] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[09Nov2020 11:42:39.352] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[09Nov2020 11:42:39.353] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1048]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[09Nov2020 11:42:39.353] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]: Caused by: java.lang.IllegalArgumentException: The specified resource 'appliedenergistics2.mixins.json' was invalid or could not be read
[09Nov2020 11:42:39.353] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1082)
[09Nov2020 11:42:39.353] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
[09Nov2020 11:42:39.353] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1057]: 	... 19 more

**Comment by BedrockLegends** [comment]
it only does it when you update to forge-1.16.3-geckolib-3.0.0-beta 8

**Comment by bernie-g** [comment]
Looks like an issue with applier energistics, not GeckoLib.

**Comment by drakray** [comment]
I got trouble with beta-8 too, [crashlog](https://pastebin.com/GZRzcCRM)

forge-1.16.3-geckolib-3.0.0-beta.8.jar is in the mods folder as shown in the log, just not loading?
reverting to 2.1.2 works
