### ISSUE TITLE
Having problem with Geckolib and Deeper And Darker

### ISSUE THREAD

**Issue by DaCurlyFKR** [bernie-g/geckolib#395]
Whenever I go into the Deeper And Darker dimension I load into it then immediatley freeze when things start rendering.

Error:

java.lang.NoSuchMethodError: 'software.bernie.geckolib3.core.manager.AnimationFactory software.bernie.geckolib3.util.GeckoLibUtil.createFactory(software.bernie.geckolib3.core.IAnimatable)'
	at com.kyanite.deeperdarker.registry.entities.custom.SculkSnapperEntity.<init>(SculkSnapperEntity.java:61) ~[deeperdarker-forge-1.1.6-forge.jar%23212!/:?] {re:classloading}
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:469) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:mixin,re:classloading,pl:mixin:APP:forge-mca.mixin.json:MixinEntityType,pl:mixin:APP:flywheel.mixins.json:EntityTypeMixin,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType,pl:mixin:A}
	at net.minecraft.world.level.NaturalSpawner.m_46988_(NaturalSpawner.java:242) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:178) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:127) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:117) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:356) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:310) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:285) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:forge-mca.mixin.json:MixinServerWorld,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23241!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

Trying to make a modpack and this has been my only issue so far.

**Comment by DaCurlyFKR** [comment]
I'll keep trying older versions, but I'm past the last Deeper And Darker update so I doubt it'll fix my problem

**Comment by DaCurlyFKR** [comment]
Figured It out, I was messing with my Modpacks Folder instead of my Mods folder. Nothing's wrong with Geckolib, It's just been a long night XD.
