### ISSUE TITLE
"Model Not Found" Error on GeckoLib v3.0.106 [1.16.5]

### ISSUE THREAD

**Issue by AdventureG147** [bernie-g/geckolib#436]
So while making my Giant Pacman entity, i attempted to make it a GeckoLib model so I can scale it. I got that working with no errors showing up, and I think I even got animations working (Up until now I didn't actually run the client to see if it did work, which is my fault). So I loaded up the client, summoned the entity and... it exited the world then crashed. I tried joining that world once again, but it saved, and crashed. When it crashed it gave me the error below. What I assume happened to the world is that when I summoned the entity, it pretty much corrupted the world. As for why it shows this error, I have been tryna search as to what's going on with it, and found nothing.

Error(s):

`Caused by: software.bernie.geckolib3.geo.exception.GeckoLibException: null: Could not find model. If you are getting this with a built mod, please just restart your game.`

`Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.minecraftservices.com/privileges` 

Crash Log:
```---- Minecraft Crash Report ----
// I feel sad now :(

Time: 5/19/23 6:40 PM
Description: Rendering entity in world

software.bernie.geckolib3.geo.exception.GeckoLibException: null: Could not find model. If you are getting this with a built mod, please just restart your game.
	at software.bernie.geckolib3.model.AnimatedGeoModel.getModel(AnimatedGeoModel.java:118) ~[geckolib-forge-1.16.5-3.0.106_mapped_parchment_2022.03.06-1.16.5.jar:3.0.106] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:182) ~[geckolib-forge-1.16.5-3.0.106_mapped_parchment_2022.03.06-1.16.5.jar:3.0.106] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:59) ~[geckolib-forge-1.16.5-3.0.106_mapped_parchment_2022.03.06-1.16.5.jar:3.0.106] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.render(EntityRendererManager.java:252) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.renderEntity(WorldRenderer.java:1224) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.renderLevel(WorldRenderer.java:1032) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:620) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:437) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1003) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:612) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:52) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:108) [forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at software.bernie.geckolib3.model.AnimatedGeoModel.getModel(AnimatedGeoModel.java:118) ~[geckolib3:3.0.106] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:182) ~[geckolib3:3.0.106] {re:classloading}
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:59) ~[geckolib3:3.0.106] {re:classloading}
-- Entity being rendered --
Details:
	Entity Type: giantpacman:giant_pacman (net.adventureg147.giantpacman.entity.custom.GiantPacmanEntity)
	Entity ID: 208
	Entity Name: entity.giantpacman.giant_pacman
	Entity's Exact location: 226.50, 4.00, -241.50
	Entity's Block location: World: (226,4,-242), Chunk: (at 2,0,14 in 14,-16; contains blocks 224,0,-256 to 239,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.adventureg147.giantpacman.entity.render.GiantPacmanRenderer@7c3ae369
	Location: 0.05,-1.62,2.85 - World: (0,-2,2), Chunk: (at 0,-1,2 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -64.6875
	Delta: 2.0742416E-5
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.render(EntityRendererManager.java:252) ~[forge:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.renderEntity(WorldRenderer.java:1224) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.renderLevel(WorldRenderer.java:1032) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.renderLevel(GameRenderer.java:620) ~[forge:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Dev'/35, l='ClientLevel', x=226.45, y=4.00, z=-244.35]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (224,4,-256), Chunk: (at 0,0,0 in 14,-16; contains blocks 224,0,-256 to 239,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 236 game time, 236 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.fillReportDetails(ClientWorld.java:462) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.fillReport(Minecraft.java:2093) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:628) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:52) ~[forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:108) [forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-recomp.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 623742336 bytes (594 MB) / 1008205824 bytes (961 MB) up to 1908932608 bytes (1820 MB)
	CPUs: 8
	JVM Flags: 2 total; -XX:+IgnoreUnrecognizedVMOptions -Xss1M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmluserdevclient
	ModLauncher naming: mcp
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1.16.5-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		client-extra.jar                                  |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		main                                              |Giant Pacman                  |giantpacman                   |NONE                |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34_mapped_parchment_2022.03.06-1|Forge                         |forge                         |36.2.34             |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106_mapped_parchment_202|GeckoLib                      |geckolib3                     |3.0.106             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: de765625-78cd-420e-a05b-c96ef7c47cfc
	Launched Version: MOD_DEV
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Apple M1 GL version 2.1 Metal - 83.1, Apple
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Apple M1
```

**Comment by AdventureG147** [comment]
Oh yea, and here is the repo: https://github.com/AdventureG147/Giant-Pacman-beta-0.1.1-1.16.5

**Comment by Tslat** [comment]
This is not a geckolib issue
You have coded your mod incorrectly
