### ISSUE TITLE
in the game it causes a weird missing textures thing

### ISSUE THREAD

**Issue by CuteCyanGirl** [bernie-g/geckolib#473]
![image](https://github.com/bernie-g/geckolib/assets/110318666/1902953b-187c-4720-8066-8f2ea71376da)

java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:444)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:266)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:308)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseSymbolsMolang(MolangParser.java:228)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseOneLine(MolangParser.java:216)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseExpression(MolangParser.java:174)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseJson(MolangParser.java:154)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:177)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:55)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:171)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:267)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:30)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:72)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:90)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.Exception: Function 'null' requires at least 3 arguments. 1 are given!
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.functions.Function.<init>(Function.java:20)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.functions.utility.Lerp.<init>(Lerp.java:9)
	... 26 more
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList$SubList.get(ArrayList.java:1149)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:306)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:282)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:439)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:266)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:308)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:283)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseSymbolsMolang(MolangParser.java:228)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseOneLine(MolangParser.java:216)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseExpression(MolangParser.java:174)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseJson(MolangParser.java:154)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:177)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:55)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:171)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:267)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:30)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:72)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:90)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList$SubList.get(ArrayList.java:1149)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:306)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:282)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.createFunction(MathBuilder.java:439)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:266)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:308)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:283)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseSymbolsMolang(MolangParser.java:228)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseOneLine(MolangParser.java:216)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseExpression(MolangParser.java:174)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseJson(MolangParser.java:154)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:177)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:55)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:171)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:267)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:30)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:72)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:90)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList$SubList.get(ArrayList.java:1149)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:306)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.shadowed.eliotlash.mclib.math.MathBuilder.parseSymbols(MathBuilder.java:309)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseSymbolsMolang(MolangParser.java:228)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseOneLine(MolangParser.java:216)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseExpression(MolangParser.java:174)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.core.molang.MolangParser.parseJson(MolangParser.java:154)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.parseExpression(JsonKeyFrameUtils.java:177)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJson(JsonKeyFrameUtils.java:54)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonKeyFrameUtils.convertJsonToRotationKeyFrames(JsonKeyFrameUtils.java:171)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.util.json.JsonAnimationUtils.deserializeJsonToAnimation(JsonAnimationUtils.java:267)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:30)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:72)
	at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:90)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
  <log4j:Event logger="journeymap" timestamp="1691252674827" level="INFO" thread="Worker-Main-9">
    <log4j:Message><![CDATA[Found @Ljourneymap/client/api/ClientPlugin;: net.blay09.mods.waystones.compat.JourneyMapAddon]]></log4j:Message>
  </log4j:Event>

**Comment by CuteCyanGirl** [comment]
also 
![image](https://github.com/bernie-g/geckolib/assets/110318666/944b8333-1e43-4529-b62a-b9da993d210b)
 heres the mod version

**Comment by Tslat** [comment]
Provide the _full_ log file
