### ISSUE TITLE
NullPointerExceptions caused by Geckolib 4.2.2 at seemingly random

### ISSUE THREAD

**Issue by SEGenjoysBlivits** [bernie-g/geckolib#489]
Greetings, I just wanted to see how Minecraft would run with Geckolib installed without actually adding any Mobs with it. And it basically just keeps crashing because of some method returning null. It seems like it usually happens when I rejoin my world or switch dimension.

Here is the crash in question:

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2023-08-31 13:43:18
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.entity.Entity.isSneaky()" because "this.currentEntity" is null
	at software.bernie.geckolib.renderer.GeoReplacedEntityRenderer.hasLabel(GeoReplacedEntityRenderer.java:384)
	at net.minecraft.client.render.entity.EntityRenderer.shadowShouldShowName(EntityRenderer.java:519)
	at net.minecraft.client.render.WorldRenderer.handler$zze000$entityculling$renderEntity(WorldRenderer.java:3451)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer.java)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1324)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1110)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:880)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at software.bernie.geckolib.renderer.GeoReplacedEntityRenderer.hasLabel(GeoReplacedEntityRenderer.java:384)
	at net.minecraft.client.render.entity.EntityRenderer.shadowShouldShowName(EntityRenderer.java:519)
	at net.minecraft.client.render.WorldRenderer.handler$zze000$entityculling$renderEntity(WorldRenderer.java:3451)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer.java)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer.java:1324)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer.java:1110)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Player877'/101, l='ClientLevel', x=638.84, y=111.98, z=-261.69]]
	Chunk stats: 4096, 39
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 211566 game time, 33558 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:458)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2406)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20
	Minecraft Version ID: 1.20
	Operating System: Linux (amd64) version 6.4.12-arch1-1
	Java Version: 17.0.8.1, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1050592048 bytes (1001 MiB) / 2598371328 bytes (2478 MiB) up to 4135583744 bytes (3944 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i5-13500
	Identifier: Intel64 Family 6 Model 191 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: AlderLake-S GT1
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x4680
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
	Graphics card #1 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #1 VRAM (MB): 8194.00
	Graphics card #1 deviceId: 0x67df
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 7885.31
	Virtual memory used (MB): 10187.47
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 0 total; 
	Fabric Mods: 
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		fabric-api: Fabric API 0.87.0+1.20.1
		fabric-api-base: Fabric API Base 0.4.30+7abfd51577
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
		fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
		fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
		fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
		fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
		fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
		fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
		fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
		fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
		fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.2.12+b3afc78b77
		fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
		fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
		fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
		fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
		fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
		fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
		fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
		fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
		fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
		fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
		fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.2+6bdb2ed077
		fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.2+6bdb2ed077
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
		fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
		fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
		fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
		fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.22
		geckolib: Geckolib 4.2.2
		gplus: gPlus 17
		immediatelyfast: ImmediatelyFast 1.1.15+1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			net_lenni0451_reflect: Reflect 1.1.0
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		minecraft: Minecraft 1.20
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 7.0.1
		renderer: Renderer 1.0
		satin: Satin 1.14.0
		sodium: Sodium 0.4.10+build.27
		sodium-extra: Sodium Extra 0.4.20+mc1.20-build.103
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		starlight: Starlight 1.1.2+fabric.dbc156f
	Launched Version: Fabric
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon RX 570 Series (polaris10, LLVM 15.0.7, DRM 3.52, 6.4.12-arch1-1) GL version 4.6 (Core Profile) Mesa 23.1.6, AMD
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric
	Current Language: en_us
	CPU: 20x 13th Gen Intel(R) Core(TM) i5-13500
	Server Running: true
	Player Count: 1 / 8; [ServerPlayerEntity['Player877'/101, l='ServerLevel[dev-4]', x=638.84, y=111.98, z=-261.69]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
#@!@# Game crashed! Crash report saved to: #@!@# /home/gfh/gPlus/run/crash-reports/crash-2023-08-31_13.43.18-client.txt

Process finished with exit code 255

**Comment by Witixin1512** [comment]
It might be better for you to join the discord for support. Having conversations is easier there.

That said, two questions:
Are you completely sure that there are no mods using GeckoLib in your modlist?
What happens if you remove `EntityCulling` ?
