### ISSUE TITLE
Village collapse

### ISSUE THREAD

**Issue by zc1108aaa** [bernie-g/geckolib#536]
[crash-2024-01-21_02.15.46-client.txt](https://github.com/bernie-g/geckolib/files/13998886/crash-2024-01-21_02.15.46-client.txt)
[Uploading latest.log…]()

**Comment by zc1108aaa** [comment]
[02:15:46] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:166) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1563) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1311) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1034) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:813) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.0.jar:?]
Caused by: java.lang.IncompatibleClassChangeError: Expected static method 'int software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.getPackedOverlay(net.minecraft.class_1309, float)'
	at com.github.klyser8.earthbounds.entity.renderer.CoalChunkEntityRenderer.render(CoalChunkEntityRenderer.java:53) ~[【物冒险-地球边界】earthbounds-1.18.2-1.1.4.jar:?]
	at com.github.klyser8.earthbounds.entity.renderer.CoalChunkEntityRenderer.render(CoalChunkEntityRenderer.java:16) ~[【物冒险-地球边界】earthbounds-1.18.2-1.1.4.jar:?]
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:206) ~[【前置-壁虎】geckolib-fabric-1.18-3.0.80.jar:?]
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.method_3936(GeoEntityRenderer.java:59) ~[【前置-壁虎】geckolib-fabric-1.18-3.0.80.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:135) ~[client-intermediary.jar:?]
	... 10 more

**Comment by Tslat** [comment]
Take this to the earthbound dev
