### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Yussir** [bernie-g/geckolib#555]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-03-11 18:39:17
Description: Rendering overlay

com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2 path $
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:512) ~[client-1.19.2-20220805.130853-srg.jar%23187!/:?] {re:classloading}
	at net.minecraft.util.GsonHelper.m_13798_(GsonHelper.java:534) ~[client-1.19.2-20220805.130853-srg.jar%23187!/:?] {re:classloading}
	at net.minecraft.util.GsonHelper.m_13794_(GsonHelper.java:554) ~[client-1.19.2-20220805.130853-srg.jar%23187!/:?] {re:classloading}
	at software.bernie.geckolib3.file.AnimationFileLoader.loadFile(AnimationFileLoader.java:47) ~[geckolib-forge-1.19-3.1.40.jar%23177!/:3.1.40] {re:classloading}
	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:25) ~[geckolib-forge-1.19-3.1.40.jar%23177!/:3.1.40] {re:classloading}
	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:72) ~[geckolib-forge-1.19-3.1.40.jar%23177!/:3.1.40] {re:classloading}
	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:90) ~[geckolib-forge-1.19-3.1.40.jar%23177!/:3.1.40] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1354) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:661) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$27.read(TypeAdapters.java:655) ~[gson-2.8.9.jar%23127!/:?] {}
	at com.google.gson.internal.bind.TypeAdapters$33$1.read(TypeAdapters.java:866) ~[gson-2.8.9.jar%23127!/:?] {}
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:510) ~[client-1.19.2-20220805.130853-srg.jar%23187!/:?] {re:classloading}
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	GeckoLib (geckolib3), Version: 3.1.40
		Issue tracker URL: https://github.com/bernie-g/geckolib/issues
		at TRANSFORMER/geckolib3@3.1.40/software.bernie.geckolib3.file.AnimationFileLoader.loadFile(AnimationFileLoader.java:47)
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19.2-20220805.130853-srg.jar%23187!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:888) ~[client-1.19.2-20220805.130853-srg.jar%23187!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23187!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23187!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.8.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1148241096 bytes (1095 MiB) / 1514143744 bytes (1444 MiB) up to 7885291520 bytes (7520 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4617
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23503.44
	Virtual memory used (MB): 15126.88
	Swap memory total (MB): 15360.00
	Swap memory used (MB): 853.69
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7520m -Xms256m
	Launched Version: forge-43.3.8
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.17, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.3.8.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.8.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.3.8.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.3.8.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.3.8.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		easy_npc_1.19.2-3.9.0.jar                         |Bo's Easy NPC                 |easy_npc                      |3.9.0               |SIDED_SETU|Manifest: NOSIGNATURE
		090909.jar                                        |Lost Addon Pack               |lost_addon_pack               |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		spartanweaponry-1.19.2-3.0.4-beta-2.jar           |Spartan Weaponry              |spartanweaponry               |3.0.4-beta-2        |SIDED_SETU|Manifest: NOSIGNATURE
		relics-1.19.2-0.4.7.5.jar                         |Relics                        |relics                        |0.4.7.5             |SIDED_SETU|Manifest: NOSIGNATURE
		Apotheosis-1.19.2-6.4.1.jar                       |Apotheosis                    |apotheosis                    |6.4.1               |SIDED_SETU|Manifest: NOSIGNATURE
		architectury-6.6.92-forge.jar                     |Architectury                  |architectury                  |6.6.92              |SIDED_SETU|Manifest: NOSIGNATURE
		simplyswords-forge-1.47.0-1.19.2.jar              |Simply Swords                 |simplyswords                  |1.47.0-1.19.2       |SIDED_SETU|Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2.jar              |Player Animator               |playeranimator                |1.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.6.0.jar                       |Balm                          |balm                          |4.6.0               |SIDED_SETU|Manifest: NOSIGNATURE
		WeaponsOfMiracles-19.1.7.37.jar                   |Weapons of Minecraft          |wom                           |19.1.7.37           |SIDED_SETU|Manifest: NOSIGNATURE
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.19.2-43.3.8-universal.jar                 |Forge                         |forge                         |43.3.8              |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		curios-forge-1.19.2-5.1.6.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.6.1      |SIDED_SETU|Manifest: NOSIGNATURE
		spartanshields-1.19.2-3.0.1.jar                   |Spartan Shields               |spartanshields                |3.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           |SIDED_SETU|Manifest: NOSIGNATURE
		waystones-forge-1.19.2-11.4.2.jar                 |Waystones                     |waystones                     |11.4.2              |SIDED_SETU|Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |SIDED_SETU|Manifest: NOSIGNATURE
		EpicFight-19.5.24.jar                             |Epic Fight                    |epicfight                     |19.5.24             |SIDED_SETU|Manifest: NOSIGNATURE
		Placebo-1.19.2-7.3.5.jar                          |Placebo                       |placebo                       |7.3.5               |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: d214d887-9071-40f8-b875-4d3e33c6b6ec
	FML: 43.3
	Forge: net.minecraftforge:43.3.8

**Comment by Tslat** [comment]
One of your mods has an invalid animation file
