### ISSUE TITLE
Regarding Fabric-NeoForge Versions

### ISSUE THREAD

**Issue by SuperStefan97** [bernie-g/geckolib#560]
As a lot of players do, I play with the new bridge between Forge and Fabric, Synitra Connector. When trying to use Gecko dependent mods, the easy solution is to use Fabric Gecko and let Sinytra convert it to a compat one with Forge Gecko... or that's how it should work. 
One flaw for this was the famous mod, Ars Nouveau, which has built-in forge gecko, so when trying to use it alongside Fabric gecko, wouldn't work. With Ars Nouveau team help, I made a jar that does not have the forge gecko, and added the fabric one manually.
When using the fabric one, the game starts up properly and even loads the world, but crashes when trying to render items (for example, the spell book) it didn't crashed just for entities (for example, dragmys from the same mod).
I reported the issue both to Ars Nouveau team and Sinytra team, and the lates recomended me notifying you as it seams to be a disparity between Fabric and Forge gecko. 
I did two different tests, the first one (https://pastebin.com/7CG3Whc3) was with the previous version when it crashed with item rendering, the second (https://pastebin.com/DvH9vatm) with the newest one that crashes with entity rendering.
I thank your team as it has helped doing awesome mods as a useful library, and maybe working this alongside Connector team may also help the whole community to be more unite. 
Thanks for checking.

**Comment by SuperStefan97** [comment]
Btw, I'm using the 1.20.1 version, forgot to add that

**Comment by drakray** [comment]
I just got a similar crash using NeoForge 101 for Mc 1.20.1, and GeckoLib 4.4.3, from Naturalist's Bear
There seem to be a 4.4.4 version on CurseForge, but only for Forge and Fabric?
https://pastebin.com/x19fQ7EA
<details>

```
Description: Rendering entity in world

java.lang.NullPointerException: Cannot read field "bone" because "snapshot" is null
	at software.bernie.geckolib.core.state.BoneSnapshot.copy(BoneSnapshot.java:55) ~[0-geckolib-1.20.1-4.4.3.jar%23484!/:4.4.3] {re:classloading}
	at software.bernie.geckolib.core.animation.AnimationController.lambda$process$5(AnimationController.java:470) ~[0-geckolib-1.20.1-4.4.3.jar%23484!/:4.4.3] {re:classloading}
	at java.util.Map.computeIfAbsent(Map.java:1054) ~[?:?] {re:mixin}
	at software.bernie.geckolib.core.animation.AnimationController.process(AnimationController.java:470) ~[0-geckolib-1.20.1-4.4.3.jar%23484!/:4.4.3] {re:classloading}
	at software.bernie.geckolib.core.animation.AnimationProcessor.tickAnimation(AnimationProcessor.java:83) ~[0-geckolib-1.20.1-4.4.3.jar%23484!/:4.4.3] {re:classloading}
	at software.bernie.geckolib.model.GeoModel.handleAnimations(GeoModel.java:165) ~[0-geckolib-1.20.1-4.4.3.jar%23484!/:4.4.3] {re:classloading,re:mixin}
	at software.bernie.geckolib.renderer.GeoEntityRenderer.actuallyRender(GeoEntityRenderer.java:219) ~[0-geckolib-1.20.1-4.4.3.jar%23484!/:4.4.3] {re:classloading}
	at software.bernie.geckolib.renderer.GeoEntityRenderer.actuallyRender(GeoEntityRenderer.java:49) ~[0-geckolib-1.20.1-4.4.3.jar%23484!/:4.4.3] {re:classloading}
	at software.bernie.geckolib.renderer.GeoRenderer.defaultRender(GeoRenderer.java:142) ~[0-geckolib-1.20.1-4.4.3.jar%23484!/:4.4.3] {re:classloading,re:mixin}
	at software.bernie.geckolib.renderer.GeoEntityRenderer.m_7392_(GeoEntityRenderer.java:151) ~[0-geckolib-1.20.1-4.4.3.jar%23484!/:4.4.3] {re:classloading}
	at com.starfish_studios.naturalist.client.renderer.BearRenderer.render(BearRenderer.java:36) ~[naturalist-4.0.3-1.20.1.jar%23766!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.starfish_studios.naturalist.client.renderer.BearRenderer.m_7392_(BearRenderer.java:20) ~[naturalist-4.0.3-1.20.1.jar%23766!/:?] {re:classloading,pl:runtimedistcleaner:A}

```
</details>

**Comment by Tslat** [comment]
Somehow Neoforge got missed
UPloading now
