### ISSUE TITLE
Cannot deserialize FormatVersion

### ISSUE THREAD

**Issue by Bonnqaz** [bernie-g/geckolib#627]
The game crashes when trying to log in.

```
Description: Rendering overlay

java.lang.RuntimeException: java.io.IOException: Cannot deserialize FormatVersion
	at software.bernie.geckolib3.file.GeoModelLoader.loadModel(GeoModelLoader.java:33) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$1(GeckoLibCache.java:75) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:92) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: java.io.IOException: Cannot deserialize FormatVersion
	at software.bernie.geckolib3.geo.raw.pojo.FormatVersion.forValue(FormatVersion.java:28) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at software.bernie.shadowed.fasterxml.jackson.databind.introspect.AnnotatedMethod.callOnWith(AnnotatedMethod.java:122) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	at software.bernie.shadowed.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:134) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	at software.bernie.shadowed.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	at software.bernie.shadowed.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	at software.bernie.shadowed.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	at software.bernie.shadowed.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1608) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	at software.bernie.shadowed.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1216) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	at software.bernie.geckolib3.geo.raw.pojo.Converter.fromJsonString(Converter.java:56) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	at software.bernie.geckolib3.file.GeoModelLoader.loadModel(GeoModelLoader.java:20) ~[geckolib-forge-1.18-3.0.57%20(1).jar%2373!/:3.0.57] {re:classloading}
	... 9 more
```

**Comment by Tslat** [comment]
You've put a json file in the wrong spot

**Comment by Tslat** [comment]
This happens when you put a json in the wrong folder (typically either animation in geo folder, or vice-versa, or item model in the geo folder, etc)
If you want further support, ask in the Discord. This is not a support platform
