### ISSUE TITLE
NPC Interaction Crash

### ISSUE THREAD

**Issue by Its-Mitzy** [bernie-g/geckolib#652]
the game said it might be caused by this mod or TCG on the Pixelmon Mod. this was the crash message.

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-11-21 22:44:57
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "com.pixelmonmod.pixelmon.battles.controller.participants.EntityParticipant.getEntity()" because the return value of "com.pixelmonmod.pixelmon.api.events.npc.NPCEvent.getNPCParticipant(java.util.List)" is null
	at com.pixelmonmod.pixelmon.api.events.npc.NPCEvent$StartBattle.<init>(NPCEvent.java:71) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading,pl:eventbus:A}
	at com.pixelmonmod.pixelmon.battles.BattleRegistry.attemptNpcBattleStartEvent(BattleRegistry.java:110) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at com.pixelmonmod.pixelmon.battles.BattleRegistry.performPreBattleChecksAndEvents(BattleRegistry.java:66) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at com.pixelmonmod.pixelmon.battles.BattleRegistry.startBattle(BattleRegistry.java:49) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity.startBattle(AbstractBattleEntity.java:132) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity.m_6532_(OccupiedPokeBallEntity.java:347) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at net.minecraft.world.entity.projectile.ThrowableProjectile.m_8119_(ThrowableProjectile.java:62) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading}
	at com.pixelmonmod.pixelmon.entities.pokeballs.PokeBallEntity.m_8119_(PokeBallEntity.java:225) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity.m_8119_(OccupiedPokeBallEntity.java:135) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:335) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:315) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:894) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:809) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:656) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:249) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Pixelmon (pixelmon), Version: 9.2.9
		Issue tracker URL: https://pixelmonmod.com/tracker.php?p=2
		at TRANSFORMER/pixelmon@9.2.9/com.pixelmonmod.pixelmon.api.events.npc.NPCEvent$StartBattle.<init>(NPCEvent.java:71)
Stacktrace:
	at com.pixelmonmod.pixelmon.api.events.npc.NPCEvent$StartBattle.<init>(NPCEvent.java:71) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading,pl:eventbus:A}
	at com.pixelmonmod.pixelmon.battles.BattleRegistry.attemptNpcBattleStartEvent(BattleRegistry.java:110) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at com.pixelmonmod.pixelmon.battles.BattleRegistry.performPreBattleChecksAndEvents(BattleRegistry.java:66) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at com.pixelmonmod.pixelmon.battles.BattleRegistry.startBattle(BattleRegistry.java:49) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity.startBattle(AbstractBattleEntity.java:132) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity.m_6532_(OccupiedPokeBallEntity.java:347) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at net.minecraft.world.entity.projectile.ThrowableProjectile.m_8119_(ThrowableProjectile.java:62) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading}
	at com.pixelmonmod.pixelmon.entities.pokeballs.PokeBallEntity.m_8119_(PokeBallEntity.java:225) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity.m_8119_(OccupiedPokeBallEntity.java:135) ~[Pixelmon-1.20.2-9.2.9-universal.jar%23172!/:9.2.9-pipe25147] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:335) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:315) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: pixelmon:occupied_pokeball (com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity)
	Entity ID: 626
	Entity Name: Combusken Poké Ball
	Entity's Exact location: 450.53, 67.46, -538.95
	Entity's Block location: World: (450,67,-539), Section: (at 2,3,5 in 28,4,-34; chunk contains blocks 448,-64,-544 to 463,319,-529), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,-64,-1024 to 511,319,-513)
	Entity's Momentum: -0.39, -0.19, 0.80
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {Air:300s,CanUpdate:1b,FallDistance:0.0f,Fire:-1s,HasBeenShot:1b,Invulnerable:0b,Motion:[-0.3918365250489351d,-0.19263929312560238d,0.7985924130834314d],OnGround:0b,Owner:[I;161746412,533415942,-1153475613,-1724561926],PortalCooldown:0,Pos:[450.5301682262451d,67.4557178914053d,-538.9521875619281d],Rotation:[23.864698f,-10.361218f],UUID:[I;1022469493,-494516949,-1727406692,-555833171]}
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:335) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:315) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:894) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:809) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:656) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:249) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['ItsMitzy'/51, l='ServerLevel[L's]', x=450.93, y=66.00, z=-539.76]]
	Chunk stats: 4372
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,62,192), Section: (at 0,14,0 in 12,3,12; chunk contains blocks 192,-64,192 to 207,319,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 117342 game time, 117342 day time
	Level name: L's
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 71159 (now: false), thunder time: 5175 (now: false)
	Known server brands: forge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:894) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:809) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:656) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:249) ~[client-1.20.2-20230921.100330-srg.jar%23176!/:?] {re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftServerClientOnly,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 474701152 bytes (452 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600X Six-Core Processor           
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 5500 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x7340
	Graphics card #0 versionInfo: DriverVersion=32.0.11027.1003
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24012.52
	Virtual memory used (MB): 18660.86
	Swap memory total (MB): 7680.00
	Swap memory used (MB): 398.59
	JVM Flags: 9 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xms6144m -Xmx6144m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['ItsMitzy'/51, l='ServerLevel[L's]', x=450.93, y=66.00, z=-539.76]]
	Data Packs: vanilla, mod:mixinextras (incompatible), mod:notenoughcrashes (incompatible), mod:fancymenu (incompatible), mod:explorerscompass (incompatible), mod:terralith, mod:melody (incompatible), mod:forge, mod:incendium, mod:structorytowers, mod:konkrete (incompatible), mod:structory, mod:journeymap (incompatible), mod:pixelmon, mod:nullscape, mod:naturescompass (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.20.2-forge-48.1.0
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 1
	ModLauncher: 10.1.1
	ModLauncher launch target: forge_client
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.2.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.1.1.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.2-48.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.1.1.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.1.1.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@48
		javafml@null
	Mod List: 
		client-1.20.2-20230921.100330-srg.jar             |Minecraft                     |minecraft                     |1.20.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mixinextras-forge-0.3.2.jar                       |MixinExtras                   |mixinextras                   |0.3.2               |DONE      |Manifest: NOSIGNATURE
		notenoughcrashes-4.4.6+1.20.2-forge.jar           |Not Enough Crashes            |notenoughcrashes              |4.4.6+1.20.2        |DONE      |Manifest: NOSIGNATURE
		fancymenu_forge_3.1.7_MC_1.20.2.jar               |FancyMenu                     |fancymenu                     |3.1.7               |DONE      |Manifest: NOSIGNATURE
		ExplorersCompass-1.20.2-1.3.6-forge.jar           |Explorer's Compass            |explorerscompass              |1.20.2-1.3.6-forge  |DONE      |Manifest: NOSIGNATURE
		Terralith_1.20.4_v2.4.11.jar                      |Terralith                     |terralith                     |2.4.11              |DONE      |Manifest: NOSIGNATURE
		melody_forge_1.0.3_MC_1.20.1-1.20.4.jar           |Melody                        |melody                        |1.0.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.20.2-48.1.0-universal.jar                 |Forge                         |forge                         |48.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Incendium_1.20.4_v5.3.4.jar                       |Incendium                     |incendium                     |5.3.4               |DONE      |Manifest: NOSIGNATURE
		Structory_Towers_1.20.2_v1.0.5.jar                |Structory: Towers             |structorytowers               |1.0.5               |DONE      |Manifest: NOSIGNATURE
		konkrete_forge_1.9.3_MC_1.20.2.jar                |Konkrete                      |konkrete                      |1.9.3               |DONE      |Manifest: NOSIGNATURE
		Structory_1.20.2_v1.3.4.jar                       |Structory                     |structory                     |1.3.4               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.20.2-5.9.18-forge.jar                |Journeymap                    |journeymap                    |5.9.18              |DONE      |Manifest: NOSIGNATURE
		Pixelmon-1.20.2-9.2.9-universal.jar               |Pixelmon                      |pixelmon                      |9.2.9               |DONE      |Manifest: NOSIGNATURE
		Nullscape_1.20.4_v1.2.4.jar                       |Nullscape                     |nullscape                     |1.2.4               |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.20.2-1.11.5-forge.jar            |Nature's Compass              |naturescompass                |1.20.2-1.11.5-forge |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 40dcc37a-9fdb-45e9-836d-17952e488d33
	FML: 48.1
	Forge: net.minecraftforge:48.1.0
	Suspected Mods: Pixelmon TCG (tcg), Minecraft (minecraft), Pixelmon (pixelmon), Gecko Lib 4 (geckolib)

**Comment by Tslat** [comment]
Pixelmon issue
