### ISSUE TITLE
Crash while using MCreator

### ISSUE THREAD

**Issue by Technobucky** [bernie-g/geckolib#655]
net.minecraft.ReportedException: Rendering overlay 
    at net.minecraft.client.renderer.GameRenderer.render([GameRenderer.java:961](file:net.minecraft.client.renderer.GameRenderer:961)) ~[forge-1.20.1-47.3.0_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 
    at net.minecraft.client.Minecraft.runTick([Minecraft.java:1146](file:net.minecraft.client.Minecraft:1146)) ~[forge-1.20.1-47.3.0_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 
    at net.minecraft.client.Minecraft.run([Minecraft.java:718](file:net.minecraft.client.Minecraft:718)) ~[forge-1.20.1-47.3.0_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 
    at net.minecraft.client.main.Main.main([Main.java:218](file:net.minecraft.client.main.Main:218)) ~[forge-1.20.1-47.3.0_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A} 
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke([NativeMethodAccessorImpl.java:77](file:jdk.internal.reflect.NativeMethodAccessorImpl:77)) ~[?:?] {} 
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke([DelegatingMethodAccessorImpl.java:43](file:jdk.internal.reflect.DelegatingMethodAccessorImpl:43)) ~[?:?] {} 
    at java.lang.reflect.Method.invoke([Method.java:569](file:java.lang.reflect.Method:569)) ~[?:?] {} 
    at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget([CommonLaunchHandler.java:111](file:net.minecraftforge.fml.loading.targets.CommonLaunchHandler:111)) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 
    at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService([CommonLaunchHandler.java:99](file:net.minecraftforge.fml.loading.targets.CommonLaunchHandler:99)) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 
    at net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.devService([ForgeClientUserdevLaunchHandler.java:19](file:net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler:19)) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 
    at net.minecraftforge.fml.loading.targets.CommonDevLaunchHandler.lambda$makeService$7([CommonDevLaunchHandler.java:135](file:net.minecraftforge.fml.loading.targets.CommonDevLaunchHandler:135)) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 
    at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch([LaunchServiceHandlerDecorator.java:30](file:cpw.mods.modlauncher.LaunchServiceHandlerDecorator:30)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.modlauncher.LaunchServiceHandler.launch([LaunchServiceHandler.java:53](file:cpw.mods.modlauncher.LaunchServiceHandler:53)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.modlauncher.LaunchServiceHandler.launch([LaunchServiceHandler.java:71](file:cpw.mods.modlauncher.LaunchServiceHandler:71)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.modlauncher.Launcher.run([Launcher.java:108](file:cpw.mods.modlauncher.Launcher:108)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.modlauncher.Launcher.main([Launcher.java:78](file:cpw.mods.modlauncher.Launcher:78)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept([BootstrapLaunchConsumer.java:26](file:cpw.mods.modlauncher.BootstrapLaunchConsumer:26)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept([BootstrapLaunchConsumer.java:23](file:cpw.mods.modlauncher.BootstrapLaunchConsumer:23)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.bootstraplauncher.BootstrapLauncher.main([BootstrapLauncher.java:141](file:cpw.mods.bootstraplauncher.BootstrapLauncher:141)) ~[bootstraplauncher-1.1.2.jar:?] {} 
Caused by: software.bernie.geckolib.GeckoLibException: randomality:geo/technobucky.geo.json: Unsupported geometry json version. Supported versions: 1.12.0 
    at software.bernie.geckolib.cache.GeckoLibCache.lambda$loadModels$2([GeckoLibCache.java:98](file:software.bernie.geckolib.cache.GeckoLibCache:98)) ~[geckolib-forge-1.20.1-4.4.2_mapped_official_1.20.1.jar%23198!/:4.4.2] {re:classloading} 
    at software.bernie.geckolib.cache.GeckoLibCache.lambda$loadResources$5([GeckoLibCache.java:112](file:software.bernie.geckolib.cache.GeckoLibCache:112)) ~[geckolib-forge-1.20.1-4.4.2_mapped_official_1.20.1.jar%23198!/:4.4.2] {re:classloading} 
    at java.util.concurrent.CompletableFuture$AsyncSupply.run([CompletableFuture.java:1768](file:java.util.concurrent.CompletableFuture:1768)) ~[?:?] {} 
    at java.util.concurrent.CompletableFuture$AsyncSupply.exec([CompletableFuture.java:1760](file:java.util.concurrent.CompletableFuture:1760)) ~[?:?] {} 
    at java.util.concurrent.ForkJoinTask.doExec([ForkJoinTask.java:373](file:java.util.concurrent.ForkJoinTask:373)) ~[?:?] {} 
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec([ForkJoinPool.java:1182](file:java.util.concurrent.ForkJoinPool:1182)) ~[?:?] {} 
    at java.util.concurrent.ForkJoinPool.scan([ForkJoinPool.java:1655](file:java.util.concurrent.ForkJoinPool:1655)) ~[?:?] {} 
    at java.util.concurrent.ForkJoinPool.runWorker([ForkJoinPool.java:1622](file:java.util.concurrent.ForkJoinPool:1622)) ~[?:?] {} 
    at java.util.concurrent.ForkJoinWorkerThread.run([ForkJoinWorkerThread.java:165](file:java.util.concurrent.ForkJoinWorkerThread:165)) ~[?:?] {} 
[10:16:35] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID c99a6605-ed10-4a31-92d0-947ddea99789 
---- Minecraft Crash Report ---- 
// Hi. I'm Minecraft, and I'm a crashaholic. 
Time: 2024-11-24 10:16:35 
Description: Rendering overlay 
software.bernie.geckolib.GeckoLibException: randomality:geo/technobucky.geo.json: Unsupported geometry json version. Supported versions: 1.12.0 
    at software.bernie.geckolib.cache.GeckoLibCache.lambda$loadModels$2([GeckoLibCache.java:98](file:software.bernie.geckolib.cache.GeckoLibCache:98)) ~[geckolib-forge-1.20.1-4.4.2_mapped_official_1.20.1.jar%23198!/:4.4.2] {re:classloading} 
    at software.bernie.geckolib.cache.GeckoLibCache.lambda$loadResources$5([GeckoLibCache.java:112](file:software.bernie.geckolib.cache.GeckoLibCache:112)) ~[geckolib-forge-1.20.1-4.4.2_mapped_official_1.20.1.jar%23198!/:4.4.2] {re:classloading} 
    at java.util.concurrent.CompletableFuture$AsyncSupply.run([CompletableFuture.java:1768](file:java.util.concurrent.CompletableFuture:1768)) ~[?:?] {} 
    at java.util.concurrent.CompletableFuture$AsyncSupply.exec([CompletableFuture.java:1760](file:java.util.concurrent.CompletableFuture:1760)) ~[?:?] {} 
    at java.util.concurrent.ForkJoinTask.doExec([ForkJoinTask.java:373](file:java.util.concurrent.ForkJoinTask:373)) ~[?:?] {} 
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec([ForkJoinPool.java:1182](file:java.util.concurrent.ForkJoinPool:1182)) ~[?:?] {} 
    at java.util.concurrent.ForkJoinPool.scan([ForkJoinPool.java:1655](file:java.util.concurrent.ForkJoinPool:1655)) ~[?:?] {} 
    at java.util.concurrent.ForkJoinPool.runWorker([ForkJoinPool.java:1622](file:java.util.concurrent.ForkJoinPool:1622)) ~[?:?] {} 
    at java.util.concurrent.ForkJoinWorkerThread.run([ForkJoinWorkerThread.java:165](file:java.util.concurrent.ForkJoinWorkerThread:165)) ~[?:?] {} 
A detailed walkthrough of the error, its code path and all known details is as follows: 
--------------------------------------------------------------------------------------- 
-- Head -- 
Thread: Render thread 
Suspected Mod: 
    GeckoLib 4 (geckolib), Version: 4.4.2 
        Issue tracker URL: https://github.com/bernie-g/geckolib/issues 
        at TRANSFORMER/geckolib@4.4.2/software.bernie.geckolib.cache.GeckoLibCache.lambda$loadModels$2([GeckoLibCache.java:98](file://transformer/geckolib@4.4.2/software.bernie.geckolib.cache.GeckoLibCache:98)) 
Stacktrace: 
    at net.minecraft.client.renderer.GameRenderer.render([GameRenderer.java:957](file:net.minecraft.client.renderer.GameRenderer:957)) ~[forge-1.20.1-47.3.0_mapped_official_1.20.1-recomp.jar%23191!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 
-- Overlay render details -- 
Details: 
    Overlay name: net.minecraftforge.client.loading.ForgeLoadingOverlay 
Stacktrace: 
    at net.minecraft.client.renderer.GameRenderer.render([GameRenderer.java:957](file:net.minecraft.client.renderer.GameRenderer:957)) ~[forge-1.20.1-47.3.0_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 
    at net.minecraft.client.Minecraft.runTick([Minecraft.java:1146](file:net.minecraft.client.Minecraft:1146)) ~[forge-1.20.1-47.3.0_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 
    at net.minecraft.client.Minecraft.run([Minecraft.java:718](file:net.minecraft.client.Minecraft:718)) ~[forge-1.20.1-47.3.0_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 
    at net.minecraft.client.main.Main.main([Main.java:218](file:net.minecraft.client.main.Main:218)) ~[forge-1.20.1-47.3.0_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A} 
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke([NativeMethodAccessorImpl.java:77](file:jdk.internal.reflect.NativeMethodAccessorImpl:77)) ~[?:?] {} 
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke([DelegatingMethodAccessorImpl.java:43](file:jdk.internal.reflect.DelegatingMethodAccessorImpl:43)) ~[?:?] {} 
    at java.lang.reflect.Method.invoke([Method.java:569](file:java.lang.reflect.Method:569)) ~[?:?] {} 
    at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget([CommonLaunchHandler.java:111](file:net.minecraftforge.fml.loading.targets.CommonLaunchHandler:111)) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 
    at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService([CommonLaunchHandler.java:99](file:net.minecraftforge.fml.loading.targets.CommonLaunchHandler:99)) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 
    at net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.devService([ForgeClientUserdevLaunchHandler.java:19](file:net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler:19)) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 
    at net.minecraftforge.fml.loading.targets.CommonDevLaunchHandler.lambda$makeService$7([CommonDevLaunchHandler.java:135](file:net.minecraftforge.fml.loading.targets.CommonDevLaunchHandler:135)) ~[fmlloader-1.20.1-47.3.0.jar:?] {} 
    at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch([LaunchServiceHandlerDecorator.java:30](file:cpw.mods.modlauncher.LaunchServiceHandlerDecorator:30)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.modlauncher.LaunchServiceHandler.launch([LaunchServiceHandler.java:53](file:cpw.mods.modlauncher.LaunchServiceHandler:53)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.modlauncher.LaunchServiceHandler.launch([LaunchServiceHandler.java:71](file:cpw.mods.modlauncher.LaunchServiceHandler:71)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.modlauncher.Launcher.run([Launcher.java:108](file:cpw.mods.modlauncher.Launcher:108)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.modlauncher.Launcher.main([Launcher.java:78](file:cpw.mods.modlauncher.Launcher:78)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept([BootstrapLaunchConsumer.java:26](file:cpw.mods.modlauncher.BootstrapLaunchConsumer:26)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept([BootstrapLaunchConsumer.java:23](file:cpw.mods.modlauncher.BootstrapLaunchConsumer:23)) ~[modlauncher-10.0.9.jar:?] {} 
    at cpw.mods.bootstraplauncher.BootstrapLauncher.main([BootstrapLauncher.java:141](file:cpw.mods.bootstraplauncher.BootstrapLauncher:141)) ~[bootstraplauncher-1.1.2.jar:?] {} 
-- Last reload -- 
Details: 
    Reload number: 1 
    Reload reason: initial 
    Finished: No 
    Packs: vanilla, mod_resources 
-- System Details -- 
Details: 
    Minecraft Version: 1.20.1 
    Minecraft Version ID: 1.20.1 
    Operating System: Windows 11 (amd64) version 10.0 
    Java Version: 17.0.12, Eclipse Adoptium 
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium 
    Memory: 212953096 bytes (203 MiB) / 438304768 bytes (418 MiB) up to 4221566976 bytes (4026 MiB) 
    CPUs: 20 
    Processor Vendor: GenuineIntel 
    Processor Name: 12th Gen Intel(R) Core(TM) i7-12700 
    Identifier: Intel64 Family 6 Model 151 Stepping 2 
    Microarchitecture: Alder Lake 
    Frequency (GHz): 2.11 
    Number of physical packages: 1 
    Number of physical CPUs: 12 
    Number of logical CPUs: 20 
    Graphics card #0 name: Meta Virtual Monitor 
    Graphics card #0 vendor: Meta Inc. 
    Graphics card #0 VRAM (MB): 0.00 
    Graphics card #0 deviceId: unknown 
    Graphics card #0 versionInfo: DriverVersion=17.12.55.198 
    Graphics card #1 name: NVIDIA GeForce RTX 3060 
    Graphics card #1 vendor: NVIDIA (0x10de) 
    Graphics card #1 VRAM (MB): 4095.00 
    Graphics card #1 deviceId: 0x2504 
    Graphics card #1 versionInfo: DriverVersion=32.0.15.6103 
    Graphics card #2 name: Intel(R) UHD Graphics 770 
    Graphics card #2 vendor: Intel Corporation (0x8086) 
    Graphics card #2 VRAM (MB): 2048.00 
    Graphics card #2 deviceId: 0x4680 
    Graphics card #2 versionInfo: DriverVersion=31.0.101.5590 
    Memory slot #0 capacity (MB): 8192.00 
    Memory slot #0 clockSpeed (GHz): 3.20 
    Memory slot #0 type: DDR4 
    Memory slot #1 capacity (MB): 8192.00 
    Memory slot #1 clockSpeed (GHz): 3.20 
    Memory slot #1 type: DDR4 
    Virtual memory max (MB): 27926.66 
    Virtual memory used (MB): 13930.47 
    Swap memory total (MB): 11827.64 
    Swap memory used (MB): 9.88 
    JVM Flags: 1 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump 
    Launched Version: MOD_DEV 
    Backend library: LWJGL version 3.3.1 build 7 
    Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 561.03, NVIDIA Corporation 
    Window size: 854x480 
    GL Caps: Using framebuffer using OpenGL 3.2 
    GL debug messages: 
    Using VBOs: Yes 
    Is Modded: Definitely; Client brand changed to 'forge' 
    Type: Client (map_client.txt) 
    Graphics mode: fast 
    Resource Packs: 
    Current Language: en_us 
    CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700 
    ModLauncher: 10.0.9+10.0.9+main.dcd20f30 
    ModLauncher launch target: forgeclientuserdev 
    ModLauncher naming: mcp 
    ModLauncher services: 
        mixin-0.8.5.jar mixin PLUGINSERVICE 
        eventbus-6.0.5.jar eventbus PLUGINSERVICE 
        fmlloader-1.20.1-47.3.0.jar slf4jfixer PLUGINSERVICE 
        fmlloader-1.20.1-47.3.0.jar object_holder_definalize PLUGINSERVICE 
        fmlloader-1.20.1-47.3.0.jar runtime_enum_extender PLUGINSERVICE 
        fmlloader-1.20.1-47.3.0.jar capability_token_subclass PLUGINSERVICE 
        accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
        fmlloader-1.20.1-47.3.0.jar runtimedistcleaner PLUGINSERVICE 
        modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
        modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
    FML Language Providers: 
        minecraft@1.0 
        lowcodefml@null 
        javafml@null 
    Mod List: 
        forge-1.20.1-47.3.0_mapped_official_1.20.1-recomp.|Minecraft                     |minecraft                     |1.20.1              |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 
                                                          |Forge                         |forge                         |47.3.0              |SIDED_SETU|Manifest: NOSIGNATURE 
        main                                              |Randomality                   |randomality                   |1.1.2               |SIDED_SETU|Manifest: NOSIGNATURE 
        geckolib-forge-1.20.1-4.4.2_mapped_official_1.20.1|GeckoLib 4                    |geckolib                      |4.4.2               |SIDED_SETU|Manifest: NOSIGNATURE 
    Crash Report UUID: c99a6605-ed10-4a31-92d0-947ddea99789 
    FML: 47.3 
    Forge: net.minecraftforge:47.3.0 
[10:16:35] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 0ad4aa06-6ab9-4d36-87ea-33c6e0068528 
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\isaac\MCreatorWorkspaces\huh\run\.\crash-reports\crash-2024-11-24_10.16.35-client.txt 
> Task :runClient FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':runClient'. 
> Process 'command 'C:\Users\isaac\.mcreator\gradle\jdks\eclipse_adoptium-17-amd64-windows\jdk-17.0.12+7\bin\java.exe'' finished with non-zero exit value -1 
* Try: 
> Run with --stacktrace option to get the stack trace. 
> Run with --info or --debug option to get more log output. 
> Run with --scan to get full insights. 
> Get more help at https://help.gradle.org. 
BUILD FAILED in 38s 
10 actionable tasks: 4 executed, 6 up-to-date

**Comment by Tslat** [comment]
Ask the people who do mcreator then
