### ISSUE TITLE
geckolib-forge-1.21.4-4.8 causing Minecraft 1.24.1 to Crash

### ISSUE THREAD

**Issue by ochoafabian18** [bernie-g/geckolib#666]
Hello, this mod is causing an error code and will not load Minecraft, I even tested this with no other mods running, and still causing it to crash, here is the crash log. 

--- Minecraft Crash Report ----
// There are four lights!

Time: 2024-12-20 11:39:09
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at TRANSFORMER/net.minecraftforge.forge@54.0.6/net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:49) ~[forge-1.21.4-54.0.6-universal.jar:?]
	at TRANSFORMER/net.minecraftforge.forge@54.0.6/net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:118) ~[forge-1.21.4-54.0.6-universal.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.Minecraft.lambda$new$7(Minecraft.java:635) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.Util.ifElse(Util.java:785) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.Minecraft.lambda$new$8(Minecraft.java:628) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.gui.screens.LoadingOverlay.render(LoadingOverlay.java:190) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:780) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.Minecraft.runTick(Minecraft.java:1239) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.Minecraft.run(Minecraft.java:836) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.main.Main.main(Main.java:240) ~[forge-1.21.4-54.0.6-client.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21.4-54.0.6/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:86) ~[fmlloader-1.21.4-54.0.6.jar!/:?]
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21.4-54.0.6/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:69) ~[fmlloader-1.21.4-54.0.6.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:77) [modlauncher-10.2.2.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:97) [modlauncher-10.2.2.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:116) [modlauncher-10.2.2.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:75) [modlauncher-10.2.2.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) [modlauncher-10.2.2.jar!/:?]
	at net.minecraftforge.bootstrap@2.1.6/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) [bootstrap-2.1.6.jar!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) [bootstrap-2.1.6.jar:2.1.6]
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) [bootstrap-2.1.6.jar:2.1.6]
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) [bootstrap-2.1.6.jar:2.1.6]
Transformer Audit:
  net.minecraft.Util
    REASON: classloading
    TRANSFORMER: OptiFine:default
  net.minecraft.client.Minecraft
    REASON: classloading
    PLUGIN: accesstransformer:BEFORE
    PLUGIN: runtimedistcleaner:AFTER
  net.minecraft.client.gui.screens.LoadingOverlay
    REASON: classloading
    TRANSFORMER: OptiFine:default
  net.minecraft.client.main.Main
    REASON: classloading
  net.minecraft.client.renderer.GameRenderer
    REASON: classloading
    TRANSFORMER: OptiFine:default
  net.minecraftforge.client.loading.ClientModLoader
    REASON: classloading
  net.minecraftforge.logging.CrashReportExtender
    REASON: classloading

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at TRANSFORMER/net.minecraftforge.forge@54.0.6/net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:52) ~[forge-1.21.4-54.0.6-universal.jar!/:?]
Transformer Audit:
  net.minecraftforge.logging.CrashReportExtender
    REASON: classloading
-- MOD sereneseasons --
Details:
	Mod File: /C:/Users/ochoa/AppData/Roaming/.minecraft/Minecraft Forge Builds/Minecraft Forge 1.21.4/mods/SereneSeasons-forge-1.21.4-10.4.0.0.jar
	Failure message: Mod sereneseasons requires glitchcore 2.3.0.1 or above
		Currently, glitchcore is not installed
	Mod Version: 10.4.0.0
	Mod Issue URL: https://github.com/Glitchfiend/SereneSeasons/issues
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at TRANSFORMER/net.minecraftforge.forge@54.0.6/net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:52) ~[forge-1.21.4-54.0.6-universal.jar:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at TRANSFORMER/net.minecraftforge.forge@54.0.6/net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:50) ~[forge-1.21.4-54.0.6-universal.jar:?]
	at TRANSFORMER/net.minecraftforge.forge@54.0.6/net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:118) ~[forge-1.21.4-54.0.6-universal.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.Minecraft.lambda$new$7(Minecraft.java:635) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.Util.ifElse(Util.java:785) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.Minecraft.lambda$new$8(Minecraft.java:628) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.gui.screens.LoadingOverlay.render(LoadingOverlay.java:190) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:780) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.Minecraft.runTick(Minecraft.java:1239) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.Minecraft.run(Minecraft.java:836) ~[forge-1.21.4-54.0.6-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.main.Main.main(Main.java:240) ~[forge-1.21.4-54.0.6-client.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21.4-54.0.6/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:86) ~[fmlloader-1.21.4-54.0.6.jar!/:?]
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21.4-54.0.6/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:69) ~[fmlloader-1.21.4-54.0.6.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:77) [modlauncher-10.2.2.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:97) [modlauncher-10.2.2.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:116) [modlauncher-10.2.2.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:75) [modlauncher-10.2.2.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) [modlauncher-10.2.2.jar!/:?]
	at net.minecraftforge.bootstrap@2.1.6/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) [bootstrap-2.1.6.jar!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) [bootstrap-2.1.6.jar:2.1.6]
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) [bootstrap-2.1.6.jar:2.1.6]
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) [bootstrap-2.1.6.jar:2.1.6]
Transformer Audit:
  net.minecraft.Util
    REASON: classloading
    TRANSFORMER: OptiFine:default
  net.minecraft.client.Minecraft
    REASON: classloading
    PLUGIN: accesstransformer:BEFORE
    PLUGIN: runtimedistcleaner:AFTER
  net.minecraft.client.gui.screens.LoadingOverlay
    REASON: classloading
    TRANSFORMER: OptiFine:default
  net.minecraft.client.main.Main
    REASON: classloading
  net.minecraft.client.renderer.GameRenderer
    REASON: classloading
    TRANSFORMER: OptiFine:default
  net.minecraftforge.client.loading.ClientModLoader
    REASON: classloading
  net.minecraftforge.logging.CrashReportExtender
    REASON: classloading

-- System Details --
Details:
	Minecraft Version: 1.21.4
	Minecraft Version ID: 1.21.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 391992544 bytes (373 MiB) / 805306368 bytes (768 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.19
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 26.20.100.7926
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 25287.92
	Virtual memory used (MiB): 10157.12
	Swap memory total (MiB): 9216.00
	Swap memory used (MiB): 46.54
	Space in storage for jna.tmpdir (MiB): available: 22858.38, total: 243218.94
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 22858.38, total: 243218.94
	Space in storage for io.netty.native.workdir (MiB): available: 22858.38, total: 243218.94
	Space in storage for java.io.tmpdir (MiB): available: 22858.38, total: 243218.94
	Space in storage for workdir (MiB): available: 22858.38, total: 243218.94
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.21.4_HD_U_J3_pre5
	OptiFine Build: 20241209-204457
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v8.4.01.1.zip
	OpenGlVersion: 4.6.0 - Build 26.20.100.7926
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 4
	ModLauncher: 10.2.2
	ModLauncher launch target: forge_client
	ModLauncher naming: mcp
	ModLauncher services: 
		/ slf4jfixer PLUGINSERVICE 
		/ runtimedistcleaner PLUGINSERVICE 
		/ runtime_enum_extender PLUGINSERVICE 
		/ object_holder_definalize PLUGINSERVICE 
		/ capability_token_subclass PLUGINSERVICE 
		/ accesstransformer PLUGINSERVICE 
		/ eventbus PLUGINSERVICE 
		/ mixin PLUGINSERVICE 
		/ OptiFine TRANSFORMATIONSERVICE 
		/ fml TRANSFORMATIONSERVICE 
		/ mixin TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@54
		javafml@54.0.6
	Mod List: 
		forge-1.21.4-54.0.6-client.jar                    |Minecraft                     |minecraft                     |1.21.4              |NONE      |Manifest: NOSIGNATURE
		forge-1.21.4-54.0.6-universal.jar                 |Forge                         |forge                         |54.0.6              |NONE      |Manifest: NOSIGNATURE

**Comment by Tslat** [comment]
Geckolib isn't even _in_ this error report
